<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAHgBAADATr+CmyVCYX7Gy17TLvskcGTOaLAvImA3giVS+reSVDyC/A2SdswzgiJp3eIcEKQR6USW5CNVzddCrUGhFrtrkFKD3ajCclaDfAPLn3mpYp79JyX+C1jULM9PMr3cxoyk2gomYGeZ2YzxLMqXOrdXW1i/LzRw4ifTZaXVNRTtFdwfxMHSTigkEqBzqOm3FdVmiqCDtZiFGAyrEmtoxiOKh/lPKOLM0aN3S2OBonlKyuxH8Smzm/FBfpSv8dYEztTEns7AIgqOR9YSYSVJdDLv7vJMoqwGs4TuUJ9Uf36UfuHa5XjEK8KaJgi8nMzEj1RruqW41mDTtqi4q3VuaCxBvHpbz4R+cDJRMEg0tNfx2/gi4xDvfqqETcpbZESNM5IaCeVH7GOtBtX+7P80FtWZAKRx2WMg066uWlqMe5zPi1hVnW0uR92Mxt7y5T36+1F2IABj5Wx1iK799iU5rDwxWAonvqV7Yx2g//uVE4Sag2N7UjMavCVYAAAAAA==');
