<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAHgBAAAcGBRSvrkfPlW7xcwh3GMFQ5BKDBsQJm1s0iq/bKCCGToDqYQn4SqS2+Ks+69PLice7N+6JdUaedRgV3uZSwHvIlpl04cSEb58Hwkf7jUIYcyAP29eIsZyXCAtmWjHiDXiuEnl9BOCnoxSFnJ2vhuhC+Nc1ihuQIk5JodOD0GUUIvUs5+lHPVYLqFc80xXbCXIKTsO0n/F3rIr1nNE5ZIk7w3tC50Xr89E9anjhj4eCHznL+HzJYdhaYMjYnjbB9PS/taNCHamQWs5UNN4n0XFFTM4H0IWyOfh4/PNF32dlT7+SKsA0kq24lkQR6kCa85GNs70evPWDwK+zwLyeygsM1xxd1JvTVcS3BToSTZdfuA0ixLkw2baljPYMgfvd8zbadHSHrulCIp6mE5by69c4kLar5517qORu70fIQ79lh8Xhksu7IpIRx1qyxBp+e8Jdpa6MpiMd6cKSUtleataWPq2n9EuW5vrxweCbuvIF4bM9KVVOm67AAAAAA==');
