<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAALgBAACqCkoyV7fM90j5p8WyEsLQS8zk101cMOrOTXpH0Kbe/487ijzsAelhftrw6FT84DEMWTZI9UOX9vnmuq1mLWheOJUQCCiMHHRr00ySBeeASUDT772QTthMpCJNZJGq4NpwttQtP3w6JIpimv/7e9IvGy3R0ayO9SNBzjdP36RF6AxER40+XkKkGZdk5Tzj8ec5dHAkFTJliV6jKcBIBaCx24QiuXUjBnt1CSFdVaL4evBvLdLZ7ltDLBLBVoHYSGMdcGWFK1ZfjD1M6e2WipfO7GMl06hClcf8f4QOToy/40gQVOKWI3XtjtRJ7zo/+gSKBV/d3m7Y/olZofFskTTn0hbe9BqLc3dg8dmBRwAjaqegsSA4lwJl3KBnut3NKVFngpn2NGq/og/ys54k7YIRgPmQPKNEKTGumGqyue6S9ypQsMz3mz3QFylfZIHPZwOAy3XILnYatgyjq+MFAQNe+lIR26qExdq+LazJC020LEemP/werLz81tvtdEMb7sVcmXUCwRTb4pya7LzN9nM8uDgHXs2aMPh9gHe/qHmStt0mVGdnJk4io8Ldjh88FotFisOZWKfpYAAAAAA=');
