<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAALgBAAALs2ruSHI4iYEanZbnLVepPwj/V9MwzbjYnoTUPXyP3FPExL7bcHBcVTu52RDXgzVhv5mDfWGRWh6zue/2NEqsJo1XuqEyCULjtELr/Kph2ZkPHjvY1MaDz+AAvzeUYF8NN+32PXgBmcIexAQuyLvApL4gw8vDHSyjawrYRjkgtUIh9t/4yxNI1G8FmZLNem5ME5y+dPGUSedKFDL229VXn6wvmQ5nFVBwkMGpz4inFnRU4WCFOGcaKKCmP/1g3+/bPTn6VS1LbvEHxiO/mSEHoxhGerWSTH+HS2o3RBpycIXtOYfu/8IiAx2SIQRXtb0YOxDtml8kU6WVHNY3FncAKVrZMkNSmhOHVoL8lHrUTMi/fW9TEQPoDccaukfEcOe7I84fO/yvzDDvf7NJAfsRfsOZhosVIjchDmxX9QUxvhCamCJ4BT8d9DavYeXX8uyC8QQjVUbS2+GI/gFiHrZAtsquj1hbhQPmsxfQjwrhJ9ZY4S8uwANMgzdUO9Qj0/o+WASR2f/B3gvE9qPhcsVQkOuyHnePyOXI+O2yxvGG/AKb0DintAAoM/2RoXqRbB9V2m8cHOUt6gAAAAA=');
