<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAABgCAAD+zZHlez0kCs26aUdXaWmgNtfs2ClP+yKr3xYdpDrmb3auI9khjepNj/33P6Fw/djEEtXR8F2++NzjxR6EP+36dQ1ht1nV+TV6eXKqtl7AVRXBwho4DGCyNvWw1GFrTqwmJ4VVZO34KJbMrNKfYM8G9r1ouyJjxWPvoQZN8vIBO8M2BJAXUrVB6cMXIgTMdBs9iUMm+YABAzNYLO8U01bNwpI+1Iji6dzzM248yHl2nX38sHcEhnibt2TiayKsnwUFjiwA6k7LiJlzi1mHELHT8JMPHrcZakHKRz2WpjV7JZYGOT7nldC7xxJ/Eig57ePcnYOALFg5NkLAfQCKwzcunGeDaIaPlRFycb+u4yWirBVbuR+cxQccvlfXB3U7oADiX1XG9thAwFwhfFjBDfzLyYjpPIAx9iG1roW61J0y5IAGVKYSs+sv6tG0h7yofjBvBGvSd4srtKCyADzFXKo6LJASxUpBAHCy+VEFah5nhRVHOOZnKDsca1lgVAmn/pBAm3sIANo+3kZoHMBbrASTZlIVSEg2Lw/L0GVzga66rc/AYON1sIkYeTSd8Qsr/YNaKBFLupMw0g3uTsibAfpUwLqoh/gRvjWSEaxuJK2nYIJyLPljHwJGDmA+/9uPfdNAbhQqGCp6DJmkW6vSSlj3UYWDFzzzfKCN+8mXCDGi9bhr4Mpf3KmInZvaXO/Ua60774fecstL/wAAAAA=');
