<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAABgCAADgXQQYmq4iZQEJIcgUBxFK3cHbOnmiDkQZgcsCWYUWHE+JQzda/KppLl9hSrm/vBZ2b2sVX089XyfJ+acJxd/Qhf8UVgZghTbyohRrG7/HeHkQF6jYROx0T/6dhB/vPJkXSFRR+UBbZCG3G2QsWEtUJLwx5fpfDOkGUtX+rBKG1NQjnXp+wCxfNYm4YToTS4j0sR5awrgrul+nb0C7HWbQyK84P8Su+raMpAwlBQDrHsF43oOV8MIvdx/Y7AUrLZZC2AmA+zSB5z+UyLFUJj8wjzCWwhDJZ0wsGNUmq4jF6H37YpZdozNkW3pQ5huISbnmHx7KPKRjUAagOXv5T6dFKXE3NJWapXKztnrl+TmOym6EYW5gGqRsHFSv+dLvHiOoMuIvrv+vDzpOVe8exm22pWnlNBM1Mgyv9sV/65IElWpg7zdIJNV84/9LXQxzHVkMbCRdhL+CiUk/0eGWpKHdin/HfUOGP50rY89VFromz3Venv06LhZe2LUVNUjXrbW52ggjs6RHE+CD3xC8TgQGObW+X2aAAXl+Qt3KA9x3wUF2cN99RDSB9oLUK2jjqCWc7tCs7nerrG4GWR5fxenWuFvR946gFue+eckAuLQSizxFP9a0XqlXvaZzHtaayu8lecFCQuS96w4u9bq+GRESkryaYRZACQ5h94WHEtjouW8JXwE4DHxYG49PwkLw6JuPHb9FbBmzqAAAAAA=');
