<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAACgCAACoTtuUhvWS61orUUgEEO9OnQDbD4XcvVBdDQzBT0YggP3tYEia9k17Qy5+nyMSDHu0wzDsjS/9FNUU8VRsEpxOXw9hhhzESfzE77WVQo/QD2RL6gi3sIlwwABlXnO2k1GRtOON6VcB5qqxs91fsAlft1eDt8te189Q5NGx+7USw1hM5sLEnJHu6GoLpBAiLGRQGJgt1ss35UhIiC+61YFuKBoXDTgSZZg5+8pNZLEpyJS3rghtzhYP5Qp+LRVhVL0X0ZTN1kEBNMUKXFaj7WfjHxVchzzJc7rIWEU0VdIvNUfXoCg0dscQDvbEjvKqj4B2kUZvhnDcWbpF2hK4ry1uUJ5VPSVo7WclK6Pt2YaUgg1YDmuEtngXH0vAl+rzoN8A6oPZItZYBR0JdTyBAJqBQunFsqhg5LttybFerFK16PSEokKF5PLdthbmIY7kRku+AaX7HwfKafNz0E5Sr7T6tBG6IuxkeqijLlV1CCKyYrqjJ2eI/ii4AZHypdvp9zO7SuxcHURTGOtlyVg5xv2dz7Kc+pbQoCOISfARanE/xkgobxqDt2J48qzYzaA3TXoYn7kcRNzSwk43VWfGcuHjYX3egZP9U2PZgXwKrQMLoSTv7kUgrtzLotxlwxX+qoXCZLv72YaZ+3HrtRwz1cUaqSZFcUZ2eDIBtyKY1BfBCEmlT38aisOf2440cmyEp7qoGmwcszP5Oy3uKTdJoVQ/oe1NAaFqSLUAAAAA');
