<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/VEBYUb3N5SWUerWEHy60G0ySZz74h9MnOsJWEkkBtkjQKAUTcu77IyGp+y19OrOHEW7qZEWGI448weIFOEl/u2ERbo9Z9HQ9hi8gqnbvUM7/lO6YvSArHW2yCcRaxVHxe7/dqYPwkzKvPDcVGbj6SM9htAZukjTk51RnkYmQLFcI1n7l/tg86vSLd89myxDlUQAAAHABAAAPXY0rnR9DS11VR/n6mkRLUI16/dL3+PUrw0tELPsoNj3FdwxEfpBfmaPUDuOD6QQ37mCjWDruk0hLxShYCJQURFlwuzHalJX+tbP+BtkM0zTN/Fs/g9kSx/kmsanvv/QgQHIWvhAZ4MR1T4RfRKY/SrtgZ3RvTbv8V6avKKlD9lEXfe7zftRibZaUrFtpHJieXQ//oGzZNQgSZQ6Mth46OQrQ6tSuRxDpUJYwlZFVTmE5BVOsWdmwDxaPzBY5NTg5Q4zXNnFlpHqGCxrY3cThITo/wZSVFvqcE1MgxPUiVQbJTLgRCWv3hZlnO4uEXWtYU59J6IVaq6Da8aA78XD4Q4Jo+TdOZvNR4O1YWlkfQTBIb7ksQU2kqgzz00f/PslXqC9j/V1UO+MO/eyJxS/LNWWRWm2e3E/xCS70B9LGxT7/lC6RanGua1e0OoxeVD+BUVrs4B0D0FR0Qkgqn9ODS2jYGs2tiPwrDNbFGHpeYgAAAAA=');
