<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/sqGiWsYilci4TODbatDixIv/bFvWdMSezxAUJXq3u2Wz3172Tze56vEONeBV4fL29ETJSFElro/0qYmxQm7eU05tlqRZ9mO6rnqzb7ZovE4h46lYycJGaf8yDME0W7gFwGqHdBUNJH5ZqVO/gK3w1sP0Mk/Z+lcQvnsdwFJNdkfVAn7SnMoKEwG6ug6xl6QVUQAAAHABAACcusOUqwxubZl91LNmxQiNUURYX+DlrPI6JyzuoYyHECg1nRej759EnKYYUAGkAD0R25QbpTchutjS7heVspPUPwpmoGPOsi8VE20FW7ePvKNeMeZ4nMjU+LPVQVl6E11clEjxS37JcN7ZLpxFGpKNS3JcJsZWmv0ux+jSvFEXGGEtuvNMVI1mt0rKRmYvmViLWPRZXL0+HlFUsrH53J9T0kaCsZclzovWKT5gI9d7zJmceteWlEuOb8linxZlFPMQVSQm/G1qhf+mz+Qox7UlaY95it211GlpBFJYMquH3zsWktgM/MiRv9yY5ZpocXjNCKH8C+RHO8rTZ+5uTtalHWRZ2jdPU3HCMvJgcHYo6pi5uHvco1uAJpWgta9cL47tR+1w7BHJFMRHnXiJR8+FJY7JWTEH9Qei7UpKTPgjZ6IuJKNTEgjysNu6LwjG2Tb0OXfd/KP5FfXQG+BqDr9aeZFAyZ9YZqjVoPQlvLt6agAAAAA=');
