<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAgCAADLSxg1e8uLolPCHQoeUTQfRwTx15Y6oD0DYHFvemWMUvuuTzRfqefpgUft9bZRkYUrs/+8dzl0cewmshuR/3EkjcmbKO6RhZNKz7zBSErDgEMRGLyaO5cP4QfzS5EelpDGBgIP4XcV7ejpGrOSETX3iJTvKmbfxLnzy5rmaGWxzuuBwV9i19qQ+dOcX7dOsbz+TVjv7kxm7necJ+z+G43Oyp4gxgDl7Qe2/RlMkQMkoKzXu2Dl025fxuIfhCe6eRlOGEPIrkH5LWpn3ZHqW3xaMx3U/vZ2X6U354gyC6RqEXdKg5XPUGTsefLLuE0olZJaTow1RWmp+I0akuQfA4GEzx4e+Qz04BGFjDodHEn/rdUz5ZmHcBthkMon33SQHqzd4hSmzQRLJBXrRU4a/96EXdIZgd1mwxZGdUr6T4LjMezLVNDin0lQIxL81Ve7xoyDzwmmHCUXhGCaswMe8rdqeeW841wh9QZpPfumKsE9GG0Ho/AD5tTd3cZLlNXJBSqrkPtjySh/wcgmXbWRA2/d2vucfiaag/ZBOgTSJ+SGH9t4FhxEp6Fe+RneYJz8K9puCtpqsoVzMQ7UIV0qXPOW2SeJWbq662wrzEa4z4DunWb2u0UqMZwikaIwFaLlx3kPyQuchbFJT6u3Wy7IS1PX8Q/Ru3L51znJ1cRjmtYuDF57cg20y07HAAAAAA==');
