<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAAAgCAAAzsMbVnbbDfRFNWa/UiHvAQDzP/2d6Yr6e4nhbvdGkHXwh9NCOtjO7D9Crh4S6TW/AVDEgmHDtqsP43OHv6FydpVbQP8TDzMBwhge3jHKfrBXBoCWKUwuZB7+rNRyC8k0vY80HZpPReLrneZYaPJESBXJzqGdn+TazCcCXdT69t/SMhCdZhQHFgwNQ3CqXKitDbaUGQhmOP3AkygEPQCcx8gtygHKhn17X+OGdfgdmDlNaK0+NB5pOHU1r3I7jjOH0FS0zJ1206nml4SQTOJiRKBcHmu6GoleGzjRnL52tbuqhTLIH4pXMM32IqKtX4MQRERcoo4B74G93BSEpx/3oeAWh3U1GUjiSH2zxguz4uwBMu9f2iIsn3MydCzts09v62Pg1jerkHDxio69PTvB8NWyX4hTEWfpWY8zhM7/QKiF2h3GqR27WTxfB8X9XKXG/qrZu8m9k/jT+99kYXIBTWGCKMSphhnaZAA6FwkN4XiDXrxHBYCVMk46lxj/aFPkxsEveZRcoum5DzQDchWbs2RZoku/IBXOdQh/XiXk+reJ+mAxjmf/kMhC0PUbo8cTBmEUy6G9kjbDnBQPdudDoYf/JYbZMN+9stovEYm2pw2Ap8aHwwUotBPDJBBzkE8rdkkaFSReGFNeKSGxWi6XrttCWjfuJbKotWd/vs/qXgP/RqFxR5sX1AAAAAA==');
