<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAABACAAAi1NjrUlCaTVoINC4KUZUSyLzjKZVdh/tsYXM3+83BAfc+L4rpyateY4pRU+z9o685M7GVVz62WK/CuYCqiNB1Dtk42s/8L3K0D4U/4f/ZJn7IoA7cwNFJnSb4tdKs6S/pnPWofDQJUEaf+gHaEWuuFpFP4XvIewNx6enTn+DMKqS0g34qaReez7ABHi0XgpQqC7yyPyOpDbNKdDOaKwBiz0e9EHh+8oFrAML5A5nWaL8VxAVtWrSy8YOgCR5XfH8Nj68TzBVOnlQwo62LbnSWgIeErjQgP01auBoW+2zZXnRosYL8zwUzBN693gGwnpnZI770BGtcigNNV0SR25lEYuvwbXzg5RbZE+CdsPuUCoE2bObO0MRI4235DJoXFDk1oM0othdQtBsOsX91c9VMVvOcMCmslPsJq0axvhmPA4xd4aJDE9junj8rLalD1Smw82zpsS89GLGVCWbYealhPV7YxovWqc/IQHdHslrnpLNvdc4ogOu+hGsnUf5OcWBXy4d13yaVTnze8HJsYndzRWoB8oqy2A7uTpfAGwtqU6uSI1cPTsk/9a5AzaUUA+fiQIYPpWMkVuKev/NU+9LkTPmeOhh+nOgo/c0oS57xCBE+R/4xCottGN5cr/eTL/S38YJYPXRR2IHalbR2STwH8dxZLaeqRkyQ8jT2OCtpNuaaKKHGLXyQiA6Ylf5LbIoAAAAA');
