<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAABACAAB+Q1/08QIM3mL2F4o6+mUvDJTV0xssh5hsSy+lLPHGW3fZs9F8Yb3vvjA4407Ccg0kO+evLRmESH10po2FwqeJz5SLlVkey+/o+INWUEtiZkX+q8x+46X9yzdvou2s1yqxmDB803sXEwEiOGtsyivVXhVbAw+r9vYpsPNnN935cBMH2jglHttiQ2xSXCXPgswN92mGViMmZ9QiKxL0EFrfFrGBUA5wRufjfA5UCLdm/w3LgIF2EkoIeKWSGPb8FdGy6Tf+sxA2ULWE5JlK5W9ptEX3W6BxXsJ49Ba9h4lM/JOTysMnOSBR+ANRokPP/VKOicvTEhO+eu4Qwwu2xBQmegJ0KDgUPVWZb7SW/7O4BGuX/4Q6BbX31iiQMWzZhCr3wSJXnnQMHahHlR1Y1cuzZGfd0kP4Dp6yt2q5DivCnuFgR26xEWncDOgqCW6ipimwqwoNW8VsjWNk08ZWVtkotRBVkFypWq/W7w0swJ2hoLOVw+72gtRAagsDOLawqDAImVsfXWTdMelsgr1EZzhnBCYKVZ3zbTUhnbBk+Cy/c3yhNql4/JzJZ4ws6nc5sxW74nfIZSEebqZn3ZjMYzx6vkjpYfJkJZ+OWxSZehgc809GRCJ2EBXQHcJBK6D+ODiOGCTUIVfARzLC27DFV2dfKLjHN9G/uacEDN8xLFOUiUcCI6+3Fb3quf5OWgfKhlwAAAAA');
