<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/VEBYUb3N5SWUerWEHy60G0ySZz74h9MnOsJWEkkBtkjQKAUTcu77IyGp+y19OrOHEW7qZEWGI448weIFOEl/u2ERbo9Z9HQ9hi8gqnbvUM7/lO6YvSArHW2yCcRaxVHxe7/dqYPwkzKvPDcVGbj6SM9htAZukjTk51RnkYmQLFcI1n7l/tg86vSLd89myxDlUQAAABACAACScoXshLk+aOqZKXkGkaQqxqsVf3fNpFjiF8vF68mySDn4yRVL2LZ4mOWFxUQHRGl70fSsLTcrh/yksExC/ZkZ+SYOZWrYXUEY2D2Zwttt3f9sIJa+45LojQVsW4igHI2G6ZJr3P62VcmNUIjNnw9MzsfKfwGCEmbttcdOEQ6fVkP1oxJlZcuoa34C/nQVTQq2EtptpD6kMOLlfIrIo6xyuLJQfX9wlE+AK1JZ3GurmXlzRzJP1ywBxuxNsRWa7AjipuFHMjQIP5KiljXcVTIyD3mQEFC7EFkGeyFv4aDbpa4Ucef1czGCPWwrDnsN8n58CBds2iQhPwQkHcdkBLOngkyo+uhZduR1jRK6Nv56QzvfHDhAGRiYTyy+AD9GNEDSgFLsoZ7+owsDqIDaCWcQC1PO/ystyoHW/wnfK5QqApjQoAvtujoU2BFUBTRpXvLr7NgW0d7vgngYDJ2rnSQrDn236a7saqLIq4UShknD3A/T66W84rcP4AXIHhdSw+enb2A4Tc/ZAynRW07JIh0xG94kKoZaVGO5p1SsiVVPK/MdoIqagZkgyo1PSPs9NYdQBjQzvu3ZNBtLVGrZCbQRekzwxAHHR2pR1h5k+tHQnXK+XOMGvuw9hAwLypXjZfNksmJwNnSdzJurqdNza07ro0iSZmspo4TB+eDbacZC+3ABT5ZpTWzjkF6HVJvpWgMAAAAA');
