<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAABACAABaeP54OrPfPI3kv4l7KFe0Uvmj1LmQwjyf9uQdD3B9f1OkQru3nQNSigTAxx31VR4OuypUe1QjstmgvkYkpW4vOcDb1EfNchkzpA7M3WAlhu1PDugRnrJdDMfKxpsr+qdlcK2XaxvukCYoJI0FF97c6amU/sn6JN6mL76AUwSf4VGnvQ8efHMy3aFPW9vqz/HBRdex11OFR6i8kmLOBq8w7tKeDXRvlU/xgo9c/WXcSMW6HgP6GOOAgjK3ZO0m2UJjCIfKCvPTKBbKJNwAbdRpYBPCltE5msBE6vbKlyQTKvlL6uYlWlmIxK6wEGdrEsj6wObWUyWWPmji4rmEw3S+qhl3AkVXnoAKG9HFpG/nRaK98ommOTmcIvWuJ5O6n6+tTqVmeAy7EZ2wHEInLFz2NPJT+icVuyvyaCIYt6NSdxxo/pP2JlsXoubGP8PCGZro2SjRnLbluUAAZvTe9XyYl7o6h5m0dEb8LpyaE9GWMPrSo0FjI6jInsOBfA9xtFboQU6LwpBfuV2gRyP5AzUSKx5sN+PDodiuO0OyqFoof50KekDTZjywf3L+wZ0m/Xd3+bpmbFv4Iznxuam21HcVS+uKPndyUM6VdIjsIBJ4AJSvm2UhJc0WgvXLao7wJ/r7SP3kcxM5+8f+YEf/VTs2CpyZO1GZ/s/QP4B1bGY23DGYHsLhRAf13l+VsYYIQswAAAAA');
