<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/Nnvcz3RG/S3jOHq/mCiK5GJh37Dd9sAHK2mQ4XXU4mmITLsiYFGWEqaTfW5mYt1r7K59A4NzPdA564Wn4KooO6sdpMCEFz3N/kP89GPYL9Er8MapCJjP6dA5lRqJBEGdg1dF364CVUwNE8WWvcQBiUawnxG0ifnbvhqBM4yJZnInlPdB6+bKsSeupnLrGDKFUQAAAAgCAAC/OixnumhTZtoJzsTbsUlnXhflEfMAcxHYI/OiGidARB/JfaGUDL/rLsvs9gimymYlDJf+WbcE4R+m53Ea4HpgH+9LyCdtSQolh2AROaQOpXICP5yr36LLeO5R1WPh7g/fbxA2pKYCjozKgoVYA6NZHQwVaqinHtve4yfDUHglyTkh7pHfHT0NNwn2M8qlWSPENK9Xn4bdpEGWmdkMPD3el6VD5g6sw3HRSDGUKMLU0L8JrtPO+zWVecs8GyF7z+GXsNuIQXqvbKXd1ZsKUtKImak5y7bRKeiQzr2BHd+EQ8+W79xMRIdzI/hfLTVKx5O1p3gmyTX2Y3FbyRH8IZhvmOKvcsA1LcJcEMKZAOd5io4ayKA/eoE4r/Mkut7V2PKKag7BE//SBl+yizD/wSZBC1OBOiP2TUOBSqjsknKxvNhWaQiimpwbdmeecw5Y7wQKDyGTMDaPnN4N2A+I0xJq2uy1pu3GYVMPdf+eprvNmmzBw8qtTUa1rZ0mwkir+/mu6mShF+QPpHWRqzTa6vGAkbUuy2U0QuhGdoeZ6McOguhcAraNu/zJdLxowfjtcwRcwv+leqjq1Y8rvH+kY1FZsTxFJuNNCQId+bnWbRWDWO/TFjlHYmGdhdY0Lk7k8umR+anPFRDZJHRm/4gJBB3CQ7Xb9AaB5Uev5hZrqhgtARlLSz9XVdRCAAAAAA==');
