<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAgCAAD55k1aEvupubpdoMPwOjRcVeyJ0bGq7C45Mt6+UGn/LvdGVSuGr0WiRCZnMu5YAco9Dxoj7vVpZfuyw6jNbe2Ube1ItT4TuYAIPbhgrrWihR+J8a+FHzrITYbYhoSmwbgKvlGzXadZ1dIO+5uUcWeDoohyf9gLrPuJ6Ghn3uD8KQy/x4B4zTmvfJ73HI6EbN+lXAukFdmI/WtBwByOZBG1fOFZWAx5c7pLrkz/inKfWKfkfHLc9ogj36gOrmXQRSFPI6wXmE9gsYJzm5MxoM+Qz5Fa+t8QoHR6q8CfazydLFl0zTe9UX4Yjr57vesGJZNxfs8hrl7mgmfqk9ZTfUZ1ENS2NEoMmiTRg6S9QKpprmEAV1+cBbHxRRn8BH/zs153452tjSIPK4vZilPSKsUrFLMJquSrP/zuQxR3gOtjglbw9QI5lyhNYgFb72vbZeFfbxCDpcx+4TStfyFL82W/YFlP0nHzq/B/NohDj/cds0UXebVVwHBSGLIpLUYWaghu+1O6IRslwF7B5jmC8+QC78aPb9iy8uygqqctUZJ4PyTvkbmQGVcmMk48sjmruhqzH38QUmpbk94dUMH/0isaStT5GxtTsagrHxU7Hmb70FHkMKY3rOULGmfOVMYgeBtqYq3Uxq95H2g9qTE2vw7ablu4xY8UROZj+6QjiHoq8xGHmW0rw1Z6AAAAAA==');
