<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAADACAAA3m+NDnI7dl3vzxki+kjUoMt+aIvmOMOEK6R1B7d//Ft9z7QisIOa5TTd75i5LTVSUNAgbXhbJMZ7rvgSlmuT/toBI6rH7XcxdkCPQp6G6ZK5UwNAFxi7pV/ydHeodYxdsuTvYnUwEqRrtysSJyz8oTfXo/vNQ5gS9asdqpp0yyEOhFivBIDT/DP0ErMqAx9CTq6RH6v6qx0tcBJVcH5U9OyLodZsSJ6P3SH5g4doTK9v1HYpPzCSBRJTFpgSrQe20diUcB5Grv6yeDAgOp6BHXYbGmxSvKVJKbNlIJaRvLy9obeV5zvZrUb/oLzaOOVMTgF64nlLE11+Su9ZL4j9w2nuWm0aWLbKQB5bxkGwNS8YLtCqDTeJIEAPJ0usuD6m7N+vgJy+2fEBP4mwhmSNhYW0VqgDgqxq+jXATipQI+UMPIKcs7GKAuGhd5idKLMEUS9vhy39LvHrPqYOX8ba9W2jszKOg5WHjmh+JvUYc3LFUMcmC5l7zMSvnHTPdMM7RjLXPVj3PPp4p2pXU4ggz8mUMYJ5N+QkrQQ3fdc1KuCoBL1stlhlh+k63s2ZeTO7tB5WNWbGbX7pacANgeind7PGY0fVUEyXTfMm4BByVDoriAvYXbdpj1Lif3qtqwp3m4kT7HzG/FO6U0gXJwfne99IBzy5kFBngsIBNIEAOPZph4CZWg6cnSwf5baStswbzmLbwutrEjUeJv+v1NEZlHsV1l/wMd4XDWdOcbt777gAAAAA=');
