<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAADgCAACKQk2ZJ1MAEyQY3918ynHzbG6O8W/gQrt30HAp8YA8Uk1iSTiCRkM+8k0Ib2mwrU2Tbhoy3iBFpDtAftwP2vnsNBQZdEBmyS+Dnpe7ifNi1Q7OKzQUHji6dCwgnRBE8HMPDHEq0z9FJpGvBskeAEGmFJoDJHqWG++zjSVcUDNtKQmD8jla9dUlknoABF7+PFis8XhZuTTf0Pib5iDpZoGGtSBWtweBuKPIBLmMDgQGHTFL5MQXDsZh1YQC1Ll0VyIdEPptAW0dG3HIJugtLSlp/DBoOGZwPj+OZWrAOUXlkoIfZSioib7PZD0wuKrN0xigwWSJAg53jehFgL8GNFtYSt+aP9qqma1xmXJJYcoMSlkId29Yb40JvQ1VaZtb6nd4MKQmzLtXR483Oh/rfykcygPWDNS+e7XX3y4/Ep9De/mbE3HumwxUgwFq0EtbVVAWc9CZskOTtG0m3bztc2dW2Y0hRWF3L7s2YcscfhRC4NiRzZtmZYGWGkbOpffnm1Sd5uakZZ61B3fR4AqO788rGo9Vjj3zL2gB92dXkrfJyp8HNM/ji/xc4GljdfvJRUTd/Kx8uVOujWtW3oYvLvYhnaOVJl0lOpCIF3aSpqr+vNEq1Fpz4OGh+zaYbQUJUBMArrH/sdqIORurnOB5WggrSMwHtEQmzgfrHGxJaW34mZyPMhGOfnVnHAJbF7cRgJGDIJ025lL9Hq1V7+ugedXzUiie+DnycSX/QY7puUqrhELBb2l6eZXHAAAAAA==');
