<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAADgCAAAYXzgGzZZfnijBA8ryk0zEqLxWnrxotv3f+K2gYxd4PSI+CGKYSDMa1R52E4+5QNDoYjbCcrt5No+OHmATjkTWNUmPmuKApcGRszdsR2Q550Oma3kWPLLpsehcDbbQsBk7TpTiyaT9FA4bqTUilLt1AS5M164qslwfrZuoSB9uL+fiRwVOMBjnwrXSFYXg23Ec/nluTorXRXYtguhRrBmFSYMFUCJlS9ol4N4hXY5HwyHKyhdSdqvbsgfvrwKpXjXFBt2Td2kClJzJ6w3t9g/q0REaDqO4+Y/1BBmsszruzp6Vp2FB978dQYM/Nm56qCdmloIgoWHtymRqUOv75V6SF8INzbjFfpYohLkvxUwbBlkbRfcTwSHsRUSQLLelHgd+v6Ybeemy+uY9DdOO6ZFR5seiaYylXQsIOow2CMwvxhX7qUIeeKJaxBYncJga9e2/Wc5B7lxaphKTjI9K6EyXd4ihUHA2onfiBTNPr7WDHNreJsgMtAhhCBjUm4zfWL3Phe6qCbVgL3JU0XwAcD2GlagLs+mCQjaY3bqr56mzX1mO5NxUGehH8yC/aTpZCZJ7/b7EjLvfB69isGfwCxvfwYMRTTVjic1KgacauIeIbOEocmXvMzREsm8qM8FjvuephsSNTvj6buBV8exuSxxKtUl0i8rHuczSpyCZptBvvPKOBHwC7tufa+TIwQJ6N1sW1IwnrDpsJ5rtyQ0UOnqOt9I9gb3cxYH4640pBKvgrYRIIl1PCYIvAAAAAA==');
