<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAgCAADrSz2IyxPPMoneaZXTBgoJceQ98oupCN9gGP1hWgz4fJGPO0T8vEh1FZk6CG5PEdKETy1fr4Gkc/NfnPJ6/W2FNAmzp85do5KFknQeMX56Ss37QxPmVYJYZfX2ClcMgwIv2f2Pa/x7krP6QeyYwhbwat+KKwmlWXGOlwlT0hCNGNQ2KqIUl/anArqbr5VYll8SWoUTuoA7ViCPOXvf2b7MHowxOAc5SMy3F7RZShF0bo0FVZ7VYnxXXbm1HT1mel9akCXVLJHROACn2wedAp7/jdy0t9siqayl49XJgUw/27mY7xYV28Wd4ypXS/WCdfIPSokFKpYw53AKFZW5X69kdbwtRabwsLd6fOGt6f4KPCQv86rpeYLgyIt0O5wWluOUraEDX/VMaqyIJ/gO1G5tWz5+KXwzS2KYzZejPtTxBWdRkuR3z51B82+bXU5DeiuO5JnCQ2XaBoY4skvVjTvrGfpP+1bcSTIMdVM6iLeSCdg+40rQYh5rdelTQkRN/01foLrCIL+uuiv6bjsD3VdG+tPof2siOssAZHErrnErjICYRIdX7Exvzi29TSkMPGTOgGQtiKUTOzGpIHW75yI0/qJVUlWTP1wS+ktTeCzMGFB0pBBwdjoGpaoy5/TMWORyTBXIHuE+JQcjEtg6UgipiD0XZbreRn2Dml7dOG9bkyr+Pa6cUnnRAAAAAA==');
