<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAACAACXJo2+EJ6sixVHAAXpUywCyqObzb/Xhqr6ADgAwgekizh5fpqeztxhYPPfXX0tEIAeYluoGz20SEupzDpxD1nfC298Xy76w27c86r8fDqjlOh/cuFV5uD5TCcP8E6+RY0+iRU9aT1kxusEmHYT8ghBDCwgCqLmxTZmIAGTKpsLm6Q5vFQm3rhLSRhBijnieNDDGO1GZT7zpyUH13AWIYx00e/W6ghfcb/gXWJ/pVtOn1dANhOcZpD/+H2Cr30yAhx+kOSDhfTEJkbylOodU1pDIY5lDFViIYCKxNEA29wNoFecj6eguDOCE7gggHjb/KzaQshq2NqjgQK134Xaiab5gsptlmE7SA4M+B6OrAGuG3YhNjwk26bSf8rBdt5ZWVTcJFikCJ1Q+8XCuLBOfCqqLPPRg+i36IyF0gyj19KrgRv4Gh0QICFjudJBR0HBKCyVKSS6hrcQIvPywS33To6KMH8jKPToUc2bKLd7Hl4AS0jlT6R6C8Q4JmVaRo7g61r+XkVEd/ElGufN70NMm+ZCcdj8LZfg8WamHko8ErKijOVscS7iph6vLk6BbzLcOHPdE7tVLAwG1yVyUsOCQhgn/olYVDymTBdwqeQc9jn3DHC1edRdLrFxciSDPoauPv+zTpGoA30uw/eMFORppgzlzA3JzEKp/9tYddapZJOucwAAAAA=');
