<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAACAADVKKxFBj+b5M6ypP1+AxaKpud7ny3E08Tw5bPTXn13c9sBoMDM480OEquBFKSjY+AJOiouPMEjFYUIdA16IrOLExHBs7PeCJ7I9euZLLhzJxz237Z9fko2GUDLPMkaZ4OMJDyMBqIJWCOnpE6pSjJ/7lzAsbJa/Edow1hHtALwerCt5xXVLkQAcQlX226TQEGWRsexb9V31smnrpuRFouk8TbRKc4qbD16SklwRQupz1FTS8p2bSgfRk47dUCAuZU0kMQWnwaVyNHSJBKyebMt2TOe9tgES6ZYFV1aYMEz4Kc9uXMIXEkZn6wXw0nAy2DhFqClrC6GWqy8vDdNR7KkkMlNmOHeB2xlDwTdfrKXZmDrTrN+47V4GrfyTCa5p0JjA4SkmtcCpl5pc9kG/p/tuXmFW+u4ZGFMWjC0xEMBPAG/dtza7EBKz2uYLuIVlYrlS0WrFaPMy6tM/jESrLUlgkKNMUvvh8YqsHblI1BoFs9HG+I31uUZgCUCfmTpeD3356VsaPwRZeOPOI6hW4rfl1OrXwzAvkn6M9P7D/7qiYjiAgovRbBVdD9icxoBbwkOOjzUhR4GpKlMNtyAaeOu8a7/YlgVsLQ8dfvW176MlAWM84L/SEck5zjz31ni6emtDHOIZ4vS6kJmJvOGjhoForKOURwvCHFbDLsf4JK8tQAAAAA=');
