<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAgCAAA6H3lvupGBQ0n4Tl40vMnkHenJD18o0MbogMsxKJxFw1VsadsLgsNpda97J6qslcSCYJVCb8W43KQipiMuYN1yad5eVijVbMLKjMzCf+c+sZBWHMBFYwjhCPonLfOVAwsEEkfmKBkXo1aTEFEIvmEo5g2Qz/g3XDBX5zz9eklL2r7jjzd0p4qp1NA6CZ3KKUboTenR/36yPLhh/K9lWpdkzeRWpUrR4Gsmvwm5P1HadyRmmHmWCf9gEhCHFKcwRsJTPgjZJ+YPvgIsEQopx/8hQa3mffaz63TBqDcDG1BA0P2GXCEAXTMGKSFE+ySvcSifjJaz0Z+PK4B146istngnXa8Uw2gB2YmhDRdpr+pVmN6txvuR+IWAKaIPJuRyocCd4taQI9R8lfrfnhMhdKr3QaQI8irixuEF9FYw+WEXVdPU9D7m5hzN2agOlXhnLIEsJp5VIh3Sl7lgcE8DlWmhnzo0voyZfM/FMBzQC9hE/TzwpfdaEPtbZWwTP5xPPqP/0VHGIqVjkvszMZoBFfp0RAWRBiQgTRm0bEKoWs1lQjRUjksCzefTFMo697NG5u5eOxpYoR1t8ikK8pCkYF4dH6VHfWTjwTQekUf2vlUsyPJqD4fvuf0JFCD9nG10JF4wiAsmM/IQ1BT/RKyjfYFiZqHXTb3cyUaOXWwv3OwEyfPoGK+tl9CeAAAAAA==');
