<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAAgCAADBEWFCOT9i9KzBgVhTZt/cZ+jyYMWxoLideeD0fuNbzGUSKUYTuYQ1VGjki4TVVl73eUZLZ1pdFMajnuQP+fvq5dT19/9J3EjfdxwktxTuLhj6Cbf+SX3Zqjxhaju+EwNxSE197QW81qzOHUbC6J+EdTjy/Yyv8aWmota1/XrkOYnpmu3rRdgQGyTxJuZ9wYArNJZI1XBD9YLAbt2tIzgfRmrD3P9ePmbJeTPKclS0aE5u+g0xuQLyUxgj2BT9/Nw6TxOYnbUQTgaIgnQ1t87iL2AQJmkJMndHGfrMjMjyYJNQzz0EweLLyuOggitt1kXDjCDWZ1HmBKQMMwGafGxWsGHCasKghn0/NbykETwaOt8o0LhzgznR/kvOf7SbyMMPsnY/ILkD8ISX1kDyE98ajqpCYOjqTw0X/3GsKrMoNY1dslylD70FHrisB5FWRVGtsD6KcNAYM/U4gesby5HG7+KAW+nU/smULa5A7ZGKkK2b4KIa1DYzrmfX3vbLGN1i9E9RyYsyY/CTWyMnHiepD7kJ0gHY1dupi8W7xZVIdJ6EEumbenTI1Rp5P3eIShhmLOD8i+gnhcqvkIx20lirmxoXzRusRXH90k6+1eN0XHwhg2GxZbOlnvbXvw9W2Bcq25OijS0ZGnmPWKQInYdUOMJSMH424iY+9HU4WbIaDAut0tHlgpz+AAAAAA==');
