<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAgCAABoU6JDg9ln0j3fiVN+LyuoXIrz/T/eU/8L5IbpxcdUpm6h9CG1CJjxCtazkfgUxW7nBIJ+MBZgu6d5ws0j/xY9TLj7bGS5SBA4rzj1+dl+IZZcLoqoq/D0U2/kx1fHweMhTfHF9AVP1kXTJYIbEcrJY4tW/pDKTVose0GDeEepsp/BhK6A+8OUIGLTN7vqNLgVIki2/OiTV5NfBNCUDTwmpjrFsyMR4FFkp+BV4KOjE2sEuuP/61SmGsfA2eK/8TRcpa66sKHcUSzNIj+X3xfcPGnwSjvza2TZvIqTZBteZ+PMm0i0vpCNF9PjYvNrV9EpAitLDUnKs5C6pAcv7HWUrXe97ZlUJCommcr7Baa/uJ4QbVkCZX3VfI5c7y4fp9VGOgyzKGV4+NBTHKp10/BMJPZFD6naEjpL4Xueefx33l/UaY/aXvWGC+JGIvhc8DssKtXq/k+jIug3cfndPSA9Fpw914wCQKAZOh8N9hbPoL810zn6sFesyTKM9H7/FDRifCw1eDUjbrVf/Fvbw5vUjYgqoVZywJSZ0kfjjBR6CJmpGEs8Q0ing8RndNQ5DpmL7GS7Y9dXSOSiLF2OyY5Xb6SgJ+SVqStQbrPovCYS3tCyemlxptFsFhilsNxwil2DgC4H7WJU5eW0Aqyq4CSgqvpAamOgXTE3ujqvdy7Oz/OH846SoIsZAAAAAA==');
