<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAAgCAACqp+nwuvdtPFtM761fAnhb72RNuRuwFevQ5OKQWXKDMicmQzRjnCe8WdVF5t+DSO/gStOuRyBwsq5GhZYLDvY4VmqdWeuMW8HOQPWJ/LN/4UCsYL4qsKnLALozaDPMnJ5+lLaKX0NSIrCFZlcpSPwobiCiyiJ/lxoPMPjJDCiSapWVGwT9IkIgywpX6je/9/Xv1harsBA+gCwTZcw2VCaln9LKTIe6odd+GgiMhEYhwCcvuUE1Zfr62VWtwbIt/bCNWjAOsa6QUD2yIeLCYz/D09sERJCxzyAtHe+MgxpJQmSJCkEJ4GOCJwbRf6EBzenpM1lvrmkLCMoxpYFmCijdEGSirAqJPPw4Vh729FfeTvwpN81GHKvGwV1DKqvYs0gvYyk9lHrljcx1/iFqh8Q0y4FGvXhVY0NbbPSgIqX4pKbM4XTL3Eb9LQT0KYjS73LP+m6rJNck23vl8ZOJBPUAXTdiz3RxQddwQMAde+d8HvffKOvolAq7Z6EN1sRDL08HnreFwtf+qNcs88JSjj8hjdQXs0ZHYc7iM9x4FjP3ikpjSPmnZrnNdHZRdfLGxewH48fLPcJz740LcqkUAaG1L9xg1hPkMwX84jxdYxQ4/upISB/YF1MGuuk7frm0mamqPLETFZ5fPiOUXt+odzq4HCdCdalRzGPXFQqv0ehFg27FFa6uCulaAAAAAA==');
