<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAACgCAAC4111fBLPVnC69wyYL3vDqZEppoLGIEfuhZCDRh98c8MVlzAMUeTtRGnBJrDg8WQO1f8S2hokQ3iFCAW0YTxXNhBYNhwr60ysY67yA6hmIowrMbkaEFUcPBAZpYBlDZSZLWy4h8Ro8fuTcp/FRg1sGmk09GQ5ZM+8FO1ecFYhTu044whhaGZAVJKXE2QpQHnrL8prsQu+1hRDomwetAyWZwA+gxf5yLbGCkffcATub7Vvqhk/OABYUjMF9wRDDnr26FI2m2g04kUdWMrtnU7cu80FecrQ3HsmtSflaSI+eE2iz/3ukxaPDcUoswavJTKgUggr8Yi+eK0VcZTiVKrVQLBgzoIX58tUb3JBDS5gFUgKl0zzhdYlq79RIvgVvSv0TLRmgArbvBREbFbaXelyWu9o+WYIiiyY+IbAqorjtcEArqJGA9W/wvqtZ9xxgrmXV3fKE1ebJmq+VvnTPWuD9DeSz6uektjHpLl4VNHB2JJDIk1gsFG+bYV/0qt2CnMUUI4L8xjh7LYjtBfwM9rXuN+5kceQFzXpZWS1dhzdVnRiUazxgasqzo0IqJUi3bb/ZF2icEjIKl6rPcs/R3ooV2mkQJ+PsXD2iU6/8814o48fsUy5YeXhlVTjrxV6NFgx86yyObjvq/32d+el2F+lbbSOgGTFwAXWmhB3rouvxKpdwdvHmAJhXh5WkfE/eENJ+POd4MmLh7f+WOAwsFanr4ttWwGdHKXUAAAAA');
