<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/Nnvcz3RG/S3jOHq/mCiK5GJh37Dd9sAHK2mQ4XXU4mmITLsiYFGWEqaTfW5mYt1r7K59A4NzPdA564Wn4KooO6sdpMCEFz3N/kP89GPYL9Er8MapCJjP6dA5lRqJBEGdg1dF364CVUwNE8WWvcQBiUawnxG0ifnbvhqBM4yJZnInlPdB6+bKsSeupnLrGDKFUQAAACgCAAAB+MWgmegxqQPb5EgSlWoKxxZSXedOMna8w/KyMCFYhAu6ztjulN9HldhjEmaZPVd5+RP2OrIiskRJ/cibqUrVEMluf8EEAUzZyijHtsodACVJBebQkg6WSCIadSMokVbOwH+QsS29aXTgiPZSjxn9xkCcnad/FGQCH3Fw3xG4hNGY4Prc6pmCYU8b5YBm7hkXJJnxHfZ88M4cfRVdPDrS7hIKNP9EG/WhZTLPTCSBMdZyLsgUsyUyGspW1tPhysNBcxLULkBYuE1ZuK3Q+De8iqz32C5Xidswrt4jKy569B3taOQqK0sNcA2cPSarEk2SBXQlYDo2qZZg69JXUeZ5FBHPa6sgoQJFN6bR+WJpVvgZTq+U0TXztOc/u5HknStEXEsaNz3ymitgqP1JVMpmJUp7v23Y++T22+gSohHw7Svgs2vVmF3fp9SQn2WC70Mgc+jtN6ssFEdmligU2X1+BYWyYBq/nKmII3zq/URnwL+Fs16xyUVJBsOYjQGhtbwzz3iq5UT7oKDfeDt9ueiT1ApM19NDwCjoKRh9JuQu/O7V6kayXvBzpnSLgkBoDhYtMZ2vrhyqSxrlxqB0KykIeRfRT/R+nOHY6G/Kp/CviibPewcTIp5V8Sg1EBwu/ZCb/mvgY8uDZeBPo3915a3/ouaaq4r8cX3+7onmYsr5ghDGTXiBXK5FSgSbLmlcaWN/zybS+mUQ/hGsrCDWOQ6jQ7ILc0F25ocAAAAA');
