<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAABACAADL+ZEu+GQFxGf0oYtCBsoGjBnMU2GquN5OPRhkyuYKnZwaRHzLTy1In8SaqXxaZneQ/yfs5aoAd3QadsL8eGSvscCQjWUvn9b5vk/S1ECr9WTehOqiBhjKa8DpTQSzGGI/a9cDppAX8y+SosQRmELEvh5PMNJZpeN0ggtBzqa7CTZJIGuHp0XmxAyyrO0lB5PC29w9VGFa/ERjyNsQ681ffjYlWARh1CFvWD0l6hdnV87yGWmTks7fCTmMVoa9XMKkenJsYJdr6e5GF4xgQ/k19o/XJ5ck/0EsQNiSoubUm0nIW30RG6C0/piWtefiEr/PbU6Ns4Z0Zjag5jav2f13iC8CNA8AYgR2bLQg7tbcvgDzPjFMSXnHFXXs4cG3a4oh/EANW3wpHjdM8UThpeorBlhl1ksmDlgDWxByVORWzwOsQE3ok+AcEFTyUHDEQ3CC2mlmhClSkP4vIspdZDJmPAkwaB14R4ToxVoS/okXqvqnHcwkf3Zz6ywGg21PFUtOpw9gphDd8+NrI5DfaNoB5fl9EWKT+p8pwrmSYagrpmH54crY1rsJDC6c3l/7RJFEG3vKRxoCge2kqfGK4pk074nuD/Zdq8x62xDlZyz/ekhQdKOQIiWfTAVzmy3yUZpOXCiP6WaJlfCzQ4lhfR0Kr0GWdhxT7K1keNtqLab+Tyrdb6GN03zVEevrpl7flCoAAAAA');
