<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/Nnvcz3RG/S3jOHq/mCiK5GJh37Dd9sAHK2mQ4XXU4mmITLsiYFGWEqaTfW5mYt1r7K59A4NzPdA564Wn4KooO6sdpMCEFz3N/kP89GPYL9Er8MapCJjP6dA5lRqJBEGdg1dF364CVUwNE8WWvcQBiUawnxG0ifnbvhqBM4yJZnInlPdB6+bKsSeupnLrGDKFUQAAABACAADAXHFfm3As4Gsdi8i8pWGDrQlp8vQLOly1CkeBYZ+ederNJw2eWZFuW4mRULx2WwPSxVIYHq1HVYf9e+nOnE+vBxlbaH8+lZM2NofAxzinsX5yHv3xIAHFcXaz+pzZ8ZTlzcfQUoEISvOo1JxS7V/WRdreNMcD45CpW/XSFukejZx7p+RNnRrwaHeX7ijo2EH/VgQBhaRHwdB3nVBz06HmUStBeLazCOiH4e0KTgAMzYKzLAGNEKTJL2Jq2s4GxUxLawWwXho+dCgJEWSOlExVZP+xyvBMIaQhxkfCgpi3XTpuv/6cIQTSeqBxnMnSNKVajcicWTBxM+I/VMEEIR2KyUtvQKbP7b219KWIAOUjLi6oKZmXzWq7qPS5YCG87QrjMQvj62AkwrrzxGcFIYISZxyt7kSDnYUhaMsygm5DD1tNkKcH+jVuTPPV9bT7x4K9HNVh3Haelq6CE8hbPj4E+diGYkvf6DpbJPylqleHYPs3NSDqAsYvgAN4ozg2ucEIRf4vvmT/HiWzvhCpAerJz/rbieVp6Xjuxr1ZyfRHnws/MOVPzopRznAbAWLvmbhFRTFAjaZsQjL5fIYiOxYzrmoqfj6UA38pNLPiBG0o1Rvr7Ti3h4gjcP477j6DK09GMe+A1eLy7FU2+UkyUSV1q34kPvVlLxvrlU3mHzQuEOqbKxBna+wqx4Hw8PXNeQcAAAAA');
