<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAABACAACSE21UxoRO8HNDeekulJc56PEm13rLd5AZwC7t5K/lN7P5yS9G+lp3zhQAiFa698YxMO4cCupsjASffA+/INFrhbG3iHO7g8sOxWrWoB/6VYsWiedUxqhTCQsTWcBnuJV1FTw464bZ2grEsSJ8Q/DZKWIylh39wS0qP58V0X0EqvGIwylgkfxhY6+s9G9FjA5dfdmMw3Q3dx/MjW3AHJeecRld4FbdiMAn8NEFltA+uHkH3QrHh1nlzYSH5qYRjBSucT7mLefRmPMKwgnacinai+bl7meAJg3KckKQTidkCMTeRO8FgWxnXL8PZTA3aDnkXAsFj/PVZp0Y8Pkpaz62uI2xckq6DQNleu63AvHI4kpsm6aWKVnPS0/FJxD46E5gOVEAIbpgccZYkLqHFS8pfEbsmli00BD2rcnSSwz28lSnk4u/3IkvtIqJyYHKrXsxLEy+JOTR1Cd7o/MJai1Lw77OAkmV7IXmFtPSsNndQcTyhIJJcPqvmYSeCy/nis6pwuV7tJhpZG7CFfgs2+NMyaI8wPIWHTGueKpyQueq5PaZxJiNnNUcOxtHzKoiQxiYjhtbpHNNeKLU38ec8pciJjaX4rrcjtWVwfWooicbTz5KIDiAoPqG1j8waBTUpl2gq09XYQUXAJpoKDOhwlhc8Wjoh8Vv3MS7SzQ3XZTabeo9zL4AC/pw7pNxhHtWWmIAAAAA');
