<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAABgCAAA6fDJM3tRUSw/Xm6Swpv1OAtwsaO6LeBgsMKS4dZKpuOIDDPQ8vJ2SDpX9idu1lAFXaWWc9FoVn1neEBKBGj4o+RRMaJ2d8dtFnpU+N7dXMTeIw+4pxNhsDkCmw2Ri+0UdZXXgwptr9J3w3u4+1PTjFvEE3OU+NP1NXPkxVnYs9YchVUjKBgBR9uETWQ+iwt0nD3l7giltmiKS9zZXPYaSGLHtswzB+hjInGu5U3BEQDLY3iV/E1FiaoMFnK0ZXM4pttqbr2ze4Jp90dpULRsIGwu2hXCdYlNB3eZH3J6stxcfKgcsjLhU9ENFwbAa9rA13f5gNCEUEslcWnKQVKdmwcUP01P5zmKEKddVGukuTQjFfFGwmpHdXqJU4VNi1g73XJOnDQEdgI2+sKawcXKByRsazsi28GVqS+oAW3BmKAkeWcSp/SzrYgPkMqzjC7Aatt4dVsuaVJwW8LdhWbjfx8v5FT+dop6XntVN3Qq/Q0xoawVdYJQpDsCzqcNM+qyPDT6dGIGtTdPCDLF9PmDVCMQuUSpqmkf+tJgZdoI2f5qpApI/7wXMRLDuwFWYAm6yMUR0XN53KF6Etaw1KbSrRzYUi1akK7pqGPQ+M9kyLfWrHg5DRXABW+nuI/53txtsmJ9RyNIZn+tjrSFFk3HHBIlYBb2lViW3DJCf9v2An7ufXMHCbN3MZbWvYQEzAZvGuxlZ2f/WMwAAAAA=');
