<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAACAABdhRw7YMCzdnNxNzcoqpRr4pu36ECtoSZ0OeiqYwr2IHSM+0OzDnCCHcv5liV9m3KMDoRf3pZorECWyitNQgpzABpOyardaiAp7uNtfjCDhd/2WhyQB1egAOsm9UKcHurkqBXbTUTd888IWDBwqB2IdCzI/pcROzVmuO+EKgpWFJYdnFs+STbtyLHTTMKbdwudc62suCOEtkHFxjBtA8bnfO/4k2NMi99REMrXTymJuj/TeKO5pDFo73X0EIJ4t/4pUlj9kKY084YLVVrx+/le/cGHjJYi0961YZeq/lXYpJzUBCvBUncpU4YRjQLRGCg9ZJU+X61F5KIW8inx60NpKLeAchVa3q5+VJdnZbnukF3t2TyzJkls1WfciZLzp7LVftBXSqcfnUvlKr0BTaxbuudft9uUHS0Tx6xUlNAYGiUjTuOXsUHdbViSYOC0hSdUkmvQX5oyVC/Emy38/gYX0AeBN354WcuZjx+ZgMRztxNmFstLf8a2J/Qe7KAp3EOSJ04n1Z1QelcGLI1Cbip+SrowGDB6bQKWL5gObEw9R/xspTZ50C8BwQiB/TfvSNE3e1mbicbGsKzdXu6uuS/Mkt4B1PTG7YaV60qmpuQ2o6/sO8EifCZq5wGNNw8upZWS5jaUvu1Tdj0SZiwo4GRKlJeS5Sjqx9SDFw8+D4zEuAAAAAA=');
