<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/sqGiWsYilci4TODbatDixIv/bFvWdMSezxAUJXq3u2Wz3172Tze56vEONeBV4fL29ETJSFElro/0qYmxQm7eU05tlqRZ9mO6rnqzb7ZovE4h46lYycJGaf8yDME0W7gFwGqHdBUNJH5ZqVO/gK3w1sP0Mk/Z+lcQvnsdwFJNdkfVAn7SnMoKEwG6ug6xl6QVUQAAABACAABanO1HLzrQq5fBdOuV5tVulQPjH/NF/DxiAZBDxunCnYW/UwpHVvPXzLQZS6vTCGwMbY2csKNWYqinnSIpwnlyowdYenxnr0eAL3JYWR5QCtItGgsNw36jti79PHe7Nz5WlbdrluByPGzreNF3nPIwdaXiKqmowOJmL8SptPvwx/+FlJKsAuRUQZ4y2jIWDWBHdALaiK5fiQjw6xugQ8/7eA1IB10PHX8xuiL9d30OadqlZ6AmOgLbXq7ZnN6aag9u4KxPOQrwPJnnQZ2ISFgaHcEe9tTlwvTwzFgXuoavBTvNUXhnznOFzh404qiE4xkHMPvLs6KBRs5HG09ONpfCKKolykWhufxMSNuiZybJ7aN0Va5R2nafYOI8raNNil5z28kapZp97sEcvSQb/m2mgp55s+V+IPiw22Ku19UOCLGB7gHickPQUlS3UNMyRVMnHoivPDdCaXhskp/yFiHlEjzdmJLbeLvnFbF4VxGkzSeXXTP+5U1IDjJ+daOj76xjy0pwEOVHuG7RYqgLInp4+j4wrB297CYHSBiyC6B9uqukKCJukuJq5Me4QaTMLhSC44a0yjSkxB/Lgav1XNJeVl9kYjKWXvpEAiz+6jAwLawMTRS6ekJaU+VyTwgnJLYrLKeg9d8QoYGEaYety9sZ4/avqbaJFo7nnFk06Dd99bXyVYK6DemYjMNzgQ0+uGwAAAAA');
