<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAgCAACaSHPbTRb0ZWjVqWkabt2n4JWrt9tU+F2v0fWf9fr9nJ3JSTQD2qg4jhOiqYbHbmkTKZop6mLUD5XT8TdHGZKdbl0ZNghCQ1xxZn5UcgHsTMzA4kDWnkj8FvD6G2mC2XigRtY+kR5y/7od6Dngrmrps1HAKcDCiXMPpC1RyIeXHkgutr+Qo+zb7YO1H87OyRVEa8sTKQHjYskj0mLyeI9dqAsNsOjW1Y3651laM6BR1NyyxE/fq7mYZ4Pcqd3eUdPZpB3XrFDOjVDi3exMzN4eorOy4N2Du/NihpzgWzJMIHsHSQy8DRW9+1pHw2RivNOa22bpRDNZUtGeZchdF1C4eUuOdATL4ixblx+9syJ1f6/AN4svaQKT1WPWn0G6DnpmW9ZlJgeGFJXlHzMEBA/b6tL6lFzL82SH6eJxP8ksmct0F0G8xJ0CF9qeABK/a++gT3lZrDDhJR5qLptqm1DHq8iPo7S2K9TzCCHfyy/4XH2Ql0hfz4Qk9t2YRwEogl98ZMcgAlDV0FodcYIEUTeZjiY2j9uCj9sEIJeo/YJlcIFVpf3OpAvFncNXAmdPydfI+hbZheiNWkrqhl4MBgaLg4B/qPypfpVUParqoRtk3v2NPgka5Qy9dst5mDhrAC2JX3us0REfNVHEcFzBlG84haPoJyKLqftuJHdKGjD4YL7rVmyFBXNRAAAAAA==');
