<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAAAgCAAB1ypN72yT9hI5YwnFsp0Wy8rJuXogEqFJQiSXM9N+N+7LmuvcDZLi4+i6oKofUKX+BNLT3fVI2bk1Uya2K4wBVYRFk9gpV/J7aZXarGAFXCfHSV/PtWfjZcEehF2uxVup0TP7F6usWqwD0n0Bc0B/tle2fBpC2GILCfGMXlVJmdslLLpPI+veCTYFoTxLqbEyVg9hUQt+y8+Dh+XXJ3lt4vajGwp3fxuNEiKEpqY/ahp6LEcA/2nD74FMqK/K0MUPqyOOpyrMtPwKQsYjkmsgWjXG4D8qNcIgk8/3/2tzeTjmf+ZH7NDIQDfj/XejRu3T4W6+yhwOPmmsy238GFbwoY6RiOVK14vMaqTW+7PtQnKx1yuef9+O0VprhXheDczdnzK3MaVQ9RcSjyUR+ZFWJhearVwN6IVS4EdUMUqAuK1IOSswWXGeGaY6q1MmK0DnwUmCguRKJFD2j+NtHr2ZU2vBnOlQqpcY8IRLoEsDPAMiHWP0ESURWeC8l+UgqYk2Ab3AEbPgVQIZAkewggVJMdVUrDD9YkioKVIqVsyembuek1aE00MPDJMcNwYGBIEKN5DKSxtKdD7anmIcwJX4z8e9aTjpw72PxgpSqCUO30qNLHyGPze/JzHN2sksyPVl67hL4hMKAblydminuxqVqbT3wUhlFvbzcCtYS/HeaUvHjfcu1gwb3AAAAAA==');
