<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAACAABlcEOdINCDq+1+cp0O9omTSN6z8buKhkH+8ooveje5qXlsF2728rJokS+xGKew7+GtGx9YRtj6qKKR1ph1j5ET5fprNVv9ACW6psH8V2rRT1My95uJbimj+aE9VdlBMFi2jgYCJrgD/veA9swqe9M3oDFoXQx/7swcJRP6C/618iZ729DmXon6Z2r6/bcTBzmbFT/3WRKlgbtvvy7bQ8S9wnb5pecAoG81aIFUCvqWP4pZhTrnaQ/NIO6i+VbpP9EaSjYo0Rrzm6WLnu7hIqWKuw902ddUipLGD5M4otj7svegWonYsDs6PspsTdYHwE/v0Py0x0CwUVnaebQX+kxluclz29l3wBgk5wkwjOOuJotPRaFZqRVtHOYLHzQOLD8d9vgXrhAoAiyV8mU2EA7Llq1SVzEmG4MZptrHbdL8qczi+xlSNYdsC8GHIhheMg8R/mSqjiMQdR9+X/PpLUOjzFvoot/3y5FoeKbtnd0uZ2ZWKHHUfREthkfsS3EtF2UktOai6FEWBJHgoGFubOolVbT2F0izp4UXkVu8VlXqeWbG+NxsVRQL7yCaHP1dpXYDaEeKb5jxcuQhuUYJfdsVgSFh5GX5eW8M3H/VSwsd5I8VZs+Tx0PKlOMpp4YAAjBUXXfO7O+Ia3fQ2YC/Jcuro8RCuBoOsNM8GDhxc77CeAAAAAA=');
