<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAACAABFMBcfxarLbb+8FTVTwsgWRna5EPFBlHjjZI4UZhSDMJjB4pMakdXxYdYPePxotUSZCSVH1FG3jQ49fVXx7wEQwVNCokl2yAjHW475+wBwrpB7+d+PHCoZtyUl/gPBzy1hAnFA3ejVejxdXRlLLlB4TjJvGTpNFC44V8ZDCtsysZeJOh/+7b+LdKBg42re2vkj9xxTHUg5fB4WWxK9HWDEC1T8BpLf2dJRh7nT9tQzQdARZxJf2LbwQnHMzu4WLHbfOxvWLt41yh6KsE13iCpFQH6xTU4Y70LYTVik3U+UqiIBpgeuiK+imKokBn8bVLrDJz6izfYmTGVwxqup3KhM2KcjproM1TfhWQuLPXbyBLIE2gf/F9X6IMTpHk/fxY+haekjUg76IxZOY4OZfRWFKsTLPr3uc/twO236t8zqsK/AHfpeg/Ex9aGDpBrL3WywAhpcstSjASnfPWepcRc0ZmdFssgNIxzfsj2FnVQEzd1jdWFogNNrwzXBC3cmV/csHX8Dm65/Hvo1UBaS3ykhljMrzkI7C5MjE6+yDLhki4DUXGulDYCZVFoFg1cREyKoTJpNmXLgsBWlzXXXtX4vnhfNx6vWq6GAHrJjrlxQatynHUStT81IIzMmGpYm2HpwGXfPrSoROuBF1kntcS3HTjyxE+JRDp6Qba/ZU/LvEAAAAAA=');
