<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAgCAABYh9U9cFPMZGLhB13L8OuAvSQlGYMyNblnsW0Xdy/3WLG04o3W+/xZ9E7Gdl6tkmcI+5wkm5SYEbioIwaF1CiltpJkRCD+0B5uJHellspm2uwJF7/OihUpTAwFgpqgRBBlIcXmct6nS5bZ9Nh8YdBhc14BWjK/YFxxec6RnFKNfYXUNQrDtgUycOoLHseMVvD1+IG7dnHwfq3KigdpnGILz6Uj/8YENONkpnTRHmFbCfnh9aI/r+NT93r+lE/596ZJNDpmgbaYAq3TyEM9H/vq28GOyjfeWprOlA9HhMPsPIGv/bzdos28HwQ30jx+TmU8n7MJUp/XszusCHomgLxN6cNzTvacecdMxTATRtXhaam6T7+gkFFxYsMso/WGQOnBD+3t5yCliW8RxQUBt0SSK28veMY5Vsv3iTT2XUStlejYza/wIZ4SbDINCnVzCtjIobB52wTVtmmuSYi851C8nq827YLy6u7+XdPat6ebcDV9ro7eGhVSu1AGCtosOSygZEtl7m+VAIqWlUBFNxhZIjJTeUOpFqsZ79jnZWIKVR4wiWWvGSeNoSEnZAQZlt99svoFwEWTPp9e/LjS3IUCjbFecLAOfDcDGqsEk7CgMXGxzNCwrnIwfWMu1myFYw/L/TbaykyjrONKc6kfmLGc8U/shiT/80oATi4zDBMtGyrNv71hEu1+AAAAAA==');
