<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAAACAACMONjLf4JJNHchMKTiLStJAV+7j8bbU0Vi0kSVaoYnBmIZtVXvjJivProubvaA2mC8KaeO/x4lnl7dv1JbRVXcZww/qPWRVixy6p7IUtOznrrz5Fp6xtnl2DImYOkZggFHEKhxjfIgYrWxqduSA3w2UIb+3TjeqQzC4rGLPrjJe/9D7v5KF8b2vQo07wDn50uLdptFswG+NFph18V2SaeFRGSV2FWeLA4/yAIrnQvr4t/eXy7sCX097hCSBm792qdqgcaL080v8KEwWsgHXRNGDbCW/Pbm+ar89gG0FUPjNNfKVEehTKNkOOnOS+uQtsXccPrhO7AoeDWq+ANV5IhyN1sN7So6VH3iGgeXV2Z/lhjYo2jod/pOOf2dFC7OkaTKxiMht1V99l476mJyMftVQDN1iLrRrjZxBZYIdhvpzkSVpCQjh+NKwUNAUrkHxdfAPh7YIQsQx+YMmZ2HquIJNFcNnj3ityqhBrEIluqtfKSTtRCt35vRuelLPD1gVu+tSv/mqs6euqGks6yPo5XGRVa8O1Upoo3be+/MYcjpYJ+G3aMjcuk/FCND7wLesm/gK+0JyCdPU+vNiXv/Edunq/zZWO2H2B5mDAlOwrTlfRNgawzWTNqXiTOLh8CKHZGnPPTtxW0qsJPx+G55a+KE8ZCaAKVi8qdGj+oUv5avRwAAAAA=');
