<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAABACAADvp6VNtiTDX4li8ben2u4gd7MMY6TE5t3mNID4mNo+QqW7O3y6reuZ2cOY+hIcdQKFX/ZlWQGnizmeJZx+Z8wwkgo6yfWsj24J5Ps7d/CA+OKzAPatUbFQ/wh9nNkShbM9pz3W/jxmRZJGwq6ZVCAfKadbxBIdK1N7ETGUtExUZU+M1zFhjjaX4Ch/za2LbaBGSmMZaZUXMOdPEGa2D/I0qM3v7YRjdfgl9fmnDXZQ5P4w7kEYTF4Js2dwdjx7Gqg/pHU0Ai90IfSrpllSb4S/31ux7WAXwhLhRnZYo8ACHVz+KrIRz6tCnEtDbSnPeb/S/SE+b/F4TlcpAkjAlQiQmsJRaUC4nWPQoYsIl51obGNlsRthNJJ7K+q4eLKHrqwenp2GuOIpiZgzM8uDSed/TkkL9NdLed5AKE+HSdv8BmSFR9xElvnxLPSCY2gUXJBq0HhinCWMEcQqWGt6c0mWIEcEkeXGA8EWNIE9wsGmSNETgYZ+u9srXPWzHO0pjtRHN5mO7snFj+EPxXVm6O4a8et98tQMh3ExboyJwZyJxJBhDitaIbQdf9qjjcMi1wMBgYj6YhzdlQd5B5UC/TMDfwd2Aa9GfNNC1ekY9MZ42ombQrKQrWhJuIh8eHVK+IYRad64wXuHaJAvEz7xLF1WcjKRCiuhD6DzEqSF9tFKekikJOR4JVQ8/hsfgmmX4PQAAAAA');
