<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAJgCAABzre2oDmsr1Y62L9ZEKkOWYn+vVBQCE50CSGXDVOMpa7GSIy4PdH6bEaw22RILl24t8C5FewzgoGkR+wd4Oxg+0Ppyyn7jorbQWXm53Bpb9lzmbHO/x4grFwcM5Jqj2C+8wy8Sv5ltMnYmXtUZluvKMwxBjPHgDtuBOqn1dD1KcghQfqnoiSk7fvZivMTlOmZQHhAO6kSA6vf73SBH7XcBC8a9/lRsykRcJyfhn/CCWJ/4fvxUui7P0VghwvpOrwneEKWe9TcsSslsVlsyFlabhmLAjPL33Yo/XBYCwcEJWD+za8vOdbnz978cECbmU+Ln6Xy5Bk7rPDqkzFUlQlFgCzVzNi07IG9Z4aRpuPAY7TjtdzbaXWvIOlDDBGNI1dnuyP6POsp7saDAIFEQrYpknpi8mLUbX2xykzRr10Zju3Zwsf/UeDsLS2bUxfWm/9NTgOOn9ss+rZgmefsoqCCb3sqGDm+QjkpAypcqZ9JoBTKXkoWO1GRS+3DjKaLX5JIsWa5K0hj3YoSN8fJytAynwBKd4X/1of2tEsNL/jEEjNxkjY7chZGUdP7TDIeBmMoSDm1BPl0oqzIDFqFefInPGWpVniboVA2ysrNtq9h2kUSejeFw3pAA1YlUHjvvUGbKWrwEVFmIa/hjWocCerMZXYt+4RORrCbxEPVv89Nl7PuHyQgJUmtdfylOyRKHqkv0cggE/+94A9JiEYknE4XYuaeRLJDgfgLeZa3ePTciqrLxE04R0W1kSD/vF8CEMwuEvp03ifdsbCOBcXk9CaA7QbvZWHV4Vjjp6hlJLkVv1ch/Clqz1uduyWwrt1St0CLHzYjuMOn9iJRtnwpj/wpfdNPrjnfI8ZXPi5Z5wi9GG0hWTQ5WsEblAAAAAA==');
