version: "3"

server:
  command: "php vendor/spiral/roadrunner-laravel/bin/rr-worker start"

rpc:
  listen: tcp://127.0.0.1:6002

logs:
  mode: production
  level: warn
  encoding: json
  output: './storage/rr.log'
  err_output: './storage/rr_errors.log'

http:
  address: 0.0.0.0:9090
  middleware: ["static", "gzip"]
  pool:
    num_workers: 0
    max_jobs: 0
    supervisor:
      max_worker_memory: 0

  static:
    dir: "public"
    forbid: [".php"]
