<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAACgCAACH+f0o2w/2tjJl2JaNrZ74dB3Nht7gdsJLlHKJ0+VwaEDwis9EZULJ4UDcYUpP7l2BkGHjNVx6mAhycd5iqH3MD+o4+w9H8c9n+6kKFLTw0ZEzl5LdFTmmx4XJtbj4dqHps/NWTkeaK9YyKSD3cM62/nIIdd2MKNxxvOL3Fkz3HYFxMqIvvbaJaTjmiYYWFPYeoMlMTB5SkyRTYowcXP9Fyg+cdf/rISJI563v3tMu2Vlv1AIkkFzC0UevD+ge18lsh2Yd/0setxmypzDZLxP1gZIsZytN5UjBcmJIqlHoAzZQSoVuV9SxGRDitcEX3wAS7czznf6VgkZgBjUkmGe8XBm7tpU+f3mqqZQJj37pWwlxQ9dTPvmDZ1/brtMmztAJqjwIrEuzf9cw2dUkc2b8TI8oIneIvilPomqiMqNdB7N/zOBxZZQ+m0KzR/U3XLhRnD3gp6kclfMpg3W254JRDxyzYU1+aFF2oICoRgoVjjmzrt2x+/fGEpDpR77AAuIZBw6URH3ZGKPbUwgAM/WRbbji8ULSC7BOFy/tX9GUmj3OljP8Z06ML5QABALHEotBwJVn4wwzX5KFKcwsm3HmxXgwFWtSf1MZMsiO8ldVoqVFjWBpLYM/iHP+7yUx/vSUm3lgmnulim5XzYBUyMPt/5cxal4JndjYP70+RqAyj1E5su+CkM7WOAz+0c0MhbamlsaylEUh2oqW+FH+et12t84NwVvRofgAAAAA');
