<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAFgBAAC3x3MBu/i3GhIYQRCj6FITYBYkg/Cp5lEhXkZCg5huL3kzcB6j/gJNWpSAnh4LYbAqefCZethAbft5lrFkl3vX+MfoeR49gOELu3+6Ej2ghGhkobv+9dm7YS5idl7dFmgixEA8gw/1NR3DXd0DH+FY7ieLIk0wO6i9NahWLMy59IEAP/X9+kxA+RQ6XsSp6jTLLTZlVO3HtUdqFj5YhCl7vLa2p+/ogv7KeDeskT1lHbTOHPV36iLPeIjSB1cF9/L6wW3reIn3nu7GbnbCz66E++zrku/4dB4zvAUiRUFmpbDt1ef3fq/MWFWn6qN/i6cBFl9GMCKVnuF++Brp0fdNUI/ESSFDPElmTjvhV8C0bJ+mKWGYx9fASzuS98rOneRVUxLyzbMrwXTnctZOd/+5bP4fLyoc34/5MLHxJY3unxE9kP13cm2L5tZ6IGEErJbaX3SFBuhLiQAAAAA=');
