<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAAFgBAABV6DeRNBSwq99/wJWs34KaKms6/uKiXFPhxPtEDdalkq8Xn6wc9J+Zusa2kJwhv2Mu+M9pewOZTJ4u6e7NUKAehRA8nK0oRdG1OgmI6oK5+1yzX6GxGfb4GLw+UZF/jxpT4h0dEUX5MFYjSssa0i+2oEAgQ72gBcXxEqQ1r2yzZsC6lN6sBO++NlLm1f2w7vKTMZAg/M8IUoWDzjBOdrazSOxs+RKm8U0E6KmycS7CUpsgyRVR3z3WR4raPZLdCg9Sm/onc6Cicvu5Bpcoo1OvOCIu4sBOMgjjW19p1ZD4zzk6TNBA48pcdoEV4ViOZU1ZuKKYGT0GkAWOhViwTXFpEc+QmtuVXzbhrYKNGkeqe5yy7HYe5n/Pc+edhwYPU6op5lBbwe4kjOXei75YxQd+dB8HlTx6ntZZUVcHqNd8GB/9HuR+fydOFmtbOX7CkewpFEQMXwnkvwAAAAA=');
