<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAFgBAADr+AgdZpqJBGxI5yQm67kGGw80702GOqzTZGhT52lhkWQnNIuePvqSUk6tKhkQ0LHa/Uuzm6VLdC+O6vlETLazthJKrVlAENXgE7hcHGDRU5IdyohAYLkQLcG7vlCoiasVs5jJTIHrAd7oCvPotiq6ktyfmxKftvrrtDzfFWmw7374bNxGgZoFEvQSyaAqf9DNXgdUbbnsdfumn9APfDchoIDVqvAM+Us6kUMc66L8tWxaRM+BwZQM04JtRN4MjtienWkoBJQHGSSq60ECkM22Plt1aNmC3kjId5kKOXweTOnJBUrlNICmrX1EG82zI5FRLeAAmvp6Gb+M4bUmIsP4iNF6wxt7YBvT4PFIgPZndd5nLz8sKF+fE6Hd2m1slfDUu2LUNXP9TI/gIMkGzPuoc21rhd4ey4z/mT391eN7NscnSJ8pncSS87t4PVJgZHg8WmZmVgGYMAAAAAA=');
