<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAHgAAAAK/T8ftqyE/qslfeW0Nu8sBxhCmjRkhoIzNO3+cNeMIhkxHodfsnTyLb68EBmSFM2+tU+RdTLIPUt04UtFy4/ujIv6s1gFerXgOuHoS5R3nsCJrMru+kl0nnATDozR475RszoDWcYmZmxp+kkwsl12VNsQSzUqRSkAAAAA');
