<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAHgAAADVP3iku0qNL8RWoKl/yZU70p8EL5qjAhQZjHop0izwNzIrEq6P33omM90TC/LnFkS41N+FhA3YEjmtOdw9QFwgK7YrHcCAXQCfZ6gXY+4qz4PUJCJVpQp0KB43pztGMVOGHAivhG36XsikMYP7ArnkO8iWJ3XJx9kAAAAA');
