<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAHgAAADBqwJ2GXLkNww6IWa9LVy6iem+3i1Es2twYqQ5Veo9+AjlG82TdVYaTaTaGu5Zpt+RLnxbLFjkpEvTy54jCwhPgtJyMoVe9XfxI86UUORXZ5VVWfGQexLH20fUZiI/rfcHwtpcqcLy3OfYJwjwxB1y3zNz/VV7H7IAAAAA');
