<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAHgAAACYdzpmljfafXqZiCe8U2IxvRLj3N9bdfgDE2J3uSRc9MyRVOXk1b4tJ/FnusyVv24xUqM625Xke1d4rSG8/W3Yzg2o7/VM6zJpoZxvyKnLNGHwyxm53eNjtlWCY/Q8JP9yo8PZ2zRQjZscqSLi850/fVseZlGDQogAAAAA');
