<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/VEBYUb3N5SWUerWEHy60G0ySZz74h9MnOsJWEkkBtkjQKAUTcu77IyGp+y19OrOHEW7qZEWGI448weIFOEl/u2ERbo9Z9HQ9hi8gqnbvUM7/lO6YvSArHW2yCcRaxVHxe7/dqYPwkzKvPDcVGbj6SM9htAZukjTk51RnkYmQLFcI1n7l/tg86vSLd89myxDlUQAAAHgAAAADYhPeYjNm50kTmYP2xkdnQe/KZDfyg/dBSdIXZKEtygejQQzk/NEM3AvND+OprNslJdlgMIuGxaTWL5JYgLqQWgU8LNzYBNVgiqveepT5JCg9Ngqm2WX2KaNQ47vMEUIP8uBzcLopjJl7gcMMdWhSoibJBBQJ0KAAAAAA');
