<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAHgAAACy+u86rS5QMSuvX8JNlW6SrQ3HZLXx1D6WP8DVb1hWcmS5hKqjurxLFEylpUUwlHmCSiu3GksWnqZdMtinTygG+DG4vl5X3IfBv4kkT/ctWoRCoJhNO/oMrUtLQvlY0OrfVJjJO47PAR47iRKB8XMPO/AWYC1PQBsAAAAA');
