<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAFgBAACG4TZ6gsFC01DKcyhyk6TkMrn2tnLIvRcUp1e2EEcXpz4v5P+9BwwWwQdH+ypLRohKjq7lObBm08EEg7j08j+f71Vky6enNbUAIXV83Y0BP/bnuBtkd0WIZA5xnzaWqnfLDBjSSQpLyLG000Myh9e9IWPVPLhrF/vV0t8OjsBX6HGwK3AwnAn+gWoByWwnEJh6+eWGymYN5huA+YuBZEDE1U48yrqp7ytdw9miMjKGsk8UbR04qRHXAg+s9xm6TQxQwtp/snJOEdIZfgDyZTt+urMPMR+8rhPHeat97fKWnFvdgmn2oUZ8ld6ajZdcSPhMPokNFw3Pp/xXhkwzMQ6fNQM6nHi9XaojXitk0GufNvZCW7JwYWXewwfssu7htfCZORtb+hK2DORVOn1/8rJ6WMjxi6ojn0pAtGkwFeEL74eiNAhVbWv2x94BM8M7scrucaWnzRO6VgAAAAA=');
