<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/VEBYUb3N5SWUerWEHy60G0ySZz74h9MnOsJWEkkBtkjQKAUTcu77IyGp+y19OrOHEW7qZEWGI448weIFOEl/u2ERbo9Z9HQ9hi8gqnbvUM7/lO6YvSArHW2yCcRaxVHxe7/dqYPwkzKvPDcVGbj6SM9htAZukjTk51RnkYmQLFcI1n7l/tg86vSLd89myxDlUQAAAFgBAACownC5u0xQ9k8XwU21GMzXYXzUBNY94V79LqYUgMNc7XA/unE8x44XRkUlUkyYsqnUVoXmaza4fgFuITX8LRtS1ZAtb/Bb9WiFEj+RR+4uWnwItrqfymxU7iCRhbNI3msMAUgoXhaP1DzKmgGcZpESXVuGn5O+hZOUTAQuDxVw6B61u4SEGNky6vGihPzzXiM96sMHIclXpcxOhDzsmxgfBgFdVbGQuMejRfsXFBXJLR5owwHYzQ8x7ehJoJ6/k12DxniBBJQSCNvpzAGYNliCxZuE0Ji379aqghQ10gwz8WhdAgdEtbCBGkgBHviLspS/GFOnrlXkDSdCf8+L+3ir60vRRU28uf+qLcccFbKQA3ArmtVeEZdAxvd2j8Po3RJVhd4EdOCOW22XrpD9p+o0uJtLdmWO7WmqOEYx1tlN5J/7CdigteCEq+bvvvpToyqIpYKqZJWhVgAAAAA=');
