<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAIgBAAAfq+nVkCp7HkQgCMOiZFQkOKMDVt9LW0lRcBECHQnRx+/Q2wBD6rF+WZgZpmIz16ERBQSR9UhDmb2ny3qjKgLGE2iqRK5NkudGFv9ptKrtlZ7hBYM9N+H5vF1kR/o9Dbz3wr0803MgsQ9/cyIppoRJ4dTRIpGQ6jDqvIAJU+KWSvI5oxzxQ3JXSsuhNHl3Hw53drsGooHbUuBA3dOkE2KS74fmnBuWdycGFAWQ8lEul/WIa9d7DFsRkLzcF4iujWyqhiDfd/bd8ysjLAk/TIY8/xCLmQ55H2LsseuiCGLLao5TwtCnpi4SysLWfVgC3bhoXKsuNVa8Sw2C6LM2SCKQHtJ9As1x1R3HsHtQnl7OR+PMsBkuF4NoEsKW2r3SOeQzjzOmKGm53cH5w78TiRRkVTeGbsiROQeIH/BPLFsv7Q6EUQFGrlGBVzuvpRFKBMx9xz6oeB/48l5GjTeFpHYv21MeHeUOb2BDgeNK5cBWjses7OigC9SCqHpaxJOskJiEuK7YBuGZQAAAAAA=');
