<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAHgBAADw4CMVg1In7O3OPJPgDR0wSZ9mFX9GkSMzwf7KGR0tiHD71BaQEo1ROIyMPlQWhl0ToZlEiiiAE2rB903plFiA5eF3CWFrGRyK8M0+u7B4rz8Gl+1LphPTE1jXLE9/9ylTZSpX25rS+QQ8URxNLYDbVj7P6d+DQCuUm8++BSUrJXJIZkzbJ0S/PiYWHiUE+l588wQdDfGUO/bKUG1pckgM2AYIOHyFx+/O/HBG/gMJ1SJCPiYScgRejEE60Xl5o9t6cwThxQ4NkZI5jI4lnfcWosvrzvnBEfQo7fxMmPN/ZGfL39nOkmkLNJXoGmKyo/X359J2KpqXolUPNT2WfaD2PiB5ithrfarwpGpgfzcpmEfo2IxDdybkO/QH8mUO/n0xsNAXLQcZBBMRUM+S4sXxY51BQ7UI9tc+oaxCVeLHHTKtpdHWcrr2YuWLolePgBUvDwu9VYEEueDGpYxxgW4g962r0WVUXXQ5uY0hNKQJCWPBwOnG3iaqAAAAAA==');
