<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAANgBAADtgc+ZOkTZHMr+u21AwUQkBfIckeYiqq9g2KAsCYbITzQWKXb9m1GQD3ENoE3B9UWkiZg8ktXUZJgfOte98QhiuvKKSMnA+9r3mmAUdkhY4nWPEPESfNY/XpdnJEa2QjMBwAv62mscsfYzCdrBKmGjYnUMa+lF+eYPutfvtQURkiehtiEwQZFjvrhOKZzngUc4e2+i7UfmHlo03VGVNCBHebRK7cB5hvQsqzm+7tIkuXa8nR+KgINrNHH4MWujMVnMxX0B2N8EM2mASazs0xqVNvkCWNuw0HrFxBALlnnKaYNvVmzYFFO2aRFXZdR19CHIFk0DaF8eeNN7wJaKIr5evm6U/61p1+KbKGWoZ4JigHYfZ16VcNGgmvbXjgTRRFQo7I73k2FiEKlDFNq8EYqfNg3ABNIQK4our80wC2EXhJpV/tqnAHlLfe6NdQ5eEFa3v2FtYc/r7DJEoMEtLUHs87PZDVnSJdQwQ0n5Ie/yU4+Nk41U2gKmjjSdQzsepPjqsOr3Ft8fnXIxjaNDcgGTX7Jii83LN5nfxPrNehdSy3OkTe5d+ruxCDaB4cgBM2ZfeICOeH/46JF0w3AWhAxxtXDggfUm6bacXpTHD3VvWz/tSKXG/RdqAAAAAA==');
