<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAMABAACa5+RxLsBM5QoKhUyi/6AeZKWnHcTn/yUkMWEq90s8IazV1rTduwAShfLzCSHzW5/OmGdrZBeDj/FNxLi2uZ7m9UMeAjcyrRCpaYg2QffaVx7iIvpbI9shq0Lk3xr4cUOZIeG1SDAaqGGKg78VADaD/XHCrU3WIekQahb/oDP965EQSTgot0zFElbYX7+ACLRKUK8dHjiU5PTq1wC+u93SW14MksODjhJd0fVvVVYjwz4/YYEPgy5SLUG5AArMj83F9NjoWDzvBy+VQV7HXTlJENbRwc4kKfeg1w5pGia+I8jJdR5dL2ZxEovZx5v6wkMVFp8J44AxBaigDblwJ2bXA+2phMRoA26GbvgM4H41uwB6mZDjK5sD9uY7Htm5MU+mvbBwNs0EYJey+alZDPa3QbkS+6du1ybyR08gSS7TReyj1qX5vqNZeHk4EBFSKRWcdq4uHCUAj0/xmhZQSgFK1pR3CK92cLQXPgVq3mECTRoQF4tehuBjYRrEDN2sVg3JU2s33CayvyD8JItfGNzc5O31IZhZBgIIkurZJurj9dkbIeF1sSMF4unAshvTAMULiOr3YxlkBgKSFGLdJqRFAAAAAA==');
