<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/Nnvcz3RG/S3jOHq/mCiK5GJh37Dd9sAHK2mQ4XXU4mmITLsiYFGWEqaTfW5mYt1r7K59A4NzPdA564Wn4KooO6sdpMCEFz3N/kP89GPYL9Er8MapCJjP6dA5lRqJBEGdg1dF364CVUwNE8WWvcQBiUawnxG0ifnbvhqBM4yJZnInlPdB6+bKsSeupnLrGDKFUQAAALgBAAB6FGCphFBausM7y2mX8xZE/1POZpykh0gYDtXaj7ieGE3PvhF3xLpx/VbGQs3h49fhkKp85r4Tta7dVpBa8KP7wiB+Sf1SDXtBQfT/ZhSGl/ltWUJto+lrNRasa4gtAgoFM+yhoLaGf0ev5aj9CGi+/reugKs7UcnI/ipmUOYOD+uXiaZKNwkglEENamr2b7qd29uvOiIkmVzkaUos6Ack+sg9js/z+91oqQba+dbh/vwEZxN7xdj/J90wrhvBTyH0g7AHDBdDhQlfywdmD56cLwSqRaYsBYtZyJqrT8d4PzaDrdinq5Ei04kqqLSBq7gMECBsz/gwwXom49rDAl0rDbD/IqvfuKorZcAV+WJIvbp9dVd4AOaf9/iw2kOJlXoQZWe+RXyAtt68xH7+iF+r8ogLMzK7AY1gtdIVHbrF9eiTD+9hTxXzUfDP2Uz1rEMRm6to/wTNXGHIp7UGDoRSgU86TruIyenE6xcw4mt1Jfb3WiMSqlOggZPK1eZbHheXawT5gVLSPTM2gJ9azwLXb+QKYOUkC7CBRZ8gem7WQxuoif29q/nNMDVhYYAM0IjWqbUVynlX8gAAAAA=');
