<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAAJABAAD2lEtJwcEYK9VNIYlchjhwRXjGIzZAfeqwHCGWI8jDgWKldgnjjyM0I+K/Gy34buq+7rjs/ZQsP3z/H3Tk4JaI7cOD8tmODEf2prSTUoKBCUErUq1OotWIifcYMa00ffscwhbXkrodJ35gH/kpmbxe/MAJeVBdDjHdACGfn1KfirDMg1NNVWy/4jcOQdc31GwHu7I8eGGI5SEvqBM/KOae2D1KVS86mpw3eCke4RQZE9EndX5u1+Mq5FRTfy9BDBof/KtgSPRLvt8C/Nq0H9+LLRHpnTd4gg9VGvyUGGT3QfJluzWTOFu/sfSQuC77XIzf/R3HhYXJEobVwbAcN6hJZc6NnuaWIV7hGXOCYD7f9Q08tTqfaBt2c+0lVwok/pnVvvk+O3Y9BNZC0uc8IowXM9chARY7a/EOYGIx6+F/iSlx/JO88kgCPqVxjRKav/MFIm5ntKhxqmyFkT2XFsqAZDZKfJph8J8538+K4aZIrg53kGEFgOVozRuGwG/qtuus16sF/ZyL8j+Bq69foxYXAAAAAA==');
