<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAJgBAAB9YkrWYwHd37jZwb+5gilYKIhtvLbbYyaZhFqsuzdbxbcENokPqop1MpXZohGqBgLxyscXWioiw0TdDUylNdpradAQqWfjP5nrd6VbNBbKmuRxV+/8VySHJ/lVEhomlfwWNZWjAX7Uh008TY+6qEzW8pYKS4r3GV3gzNMf+YBQVN1cDGIHkoSVTMfnkPqrkzDiMVv9JT+L7OuMPOEjGq5JEuwuDvoS3eNqVqVx/LYbbEd/v7CHinZ010iGusUH7i/+H1jDr/BGiW3mEHy3oHqNZLZN3mvpXXSoq5B0+65tgVdfQHRBvyd5tHMDXCVbymiFc6D//LOY+6zXr9wyIUB/Hemn1D4H0teMxdQWic8noAo+LOVr+6MRiwfhSXQF+Rb6msL6JMTUCsFEF/1CKltGMl/iVEgZ3VMhgD7Mo0f7o9wpncN2/gQi5NTMbimGDkAde/cBDmLVyDWI48G/Oi9qtvBAs0uTznkLgm1WHqx2qihwpDzguciuE1Gz8Qr28wAPeXpLUyOGjYCP21Zr1VrD6S5/jJ88RHYAAAAA');
