<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAALABAABEXKiqulx42RMaTctp2OiKOuGXg+b7yayEliwbBsnI+2lXJhjDs6SLsI2jD5yemXGO+uJ6t6UOgI5UxG4moRrqzwgCAlkzV7YMzE+WA3sKhJLSoxSn0tTvEzb2QoltsmcDkGdJkKMIMbKODoruPC15QLZjLvmr+xn4hVWR+tLC3qk98k0uuH/X3jLjtRANZSUzyvK1ieUX7IOi+rtWvCQyRBvFqnuaLdTORgEKecdSS+ZLII8Ey4KBTBPfSS2KAP3PYmC3g5eppTUvbQzQ3e3jwEXvblHavGRGVLvnJt0nfNvJclK3vf6tMl0uFpRo1r9WootaUbbv8832E235GQDLY/go+hQeC6/k2UT2UyqnBHNgh5g/GFKufZZypbZ2MPxbwwyA0v956rKe5uMuChkqU6vGFL3wiDF0hoBf+GS51rIBVWTvqzACXIGf7y+laXsm03zvBRrzzXvGt+B4z6QJgVOISRGPloMDViHzwQSBuPwqHo48BFNUKXXiB/llBdSe+k6jQCGYYkI6eNNUQO2izlKRx68nXBa+5R0l8OeA8MRuk5+JvPAIUKrl2Nv2Q1wAAAAA');
