<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAJABAAADXdSZmeSJ24ZBmAojCymY6o1ZvanTgfsvtUWtD3ZfUZz2o+NatKwwvx5gW25jdCD3jmCAKFYz+5T1Pu1/dMhjdeJwiWx+3shWM2gsirlnLJI55i7JuNm+6qtA+Z+xSC2BVLbNtVqpNI6IJlxDDqEcgeizmbuADTSMsnbz2hZ05u5UORSbwAQlbI0WwQCE5Wx/mUbqZD4yKTVZQcRyWxj8n72TWYOTIfw7qwU5mfmKeqUMCco7GMX6CUdQhwvj35KeVFriarLTabRPz4XrCo5A/ahl9WutB44DMudCDEfdZ6pQHH1D8OY9Ed6R4pHFQe/yYy5gu8XvTQmDdLZzuLSCFOpFOfOSSDp9NBB06jYQxZFzT6AgS+5TpEAdQ7WlmMkBzTmT0e2LFMzk2kcJmsIf8FnilszlvcGf+dsqa6JpzMOcW2v7KVjpgOwvZm/1aDSgcJUbXnqZW4bw01uSko/Imy8aH4JO6p6FQcJD5moJMICh/lq6kokQoz+ea3vFd9J1nj2Z+i8uiKow6f/gc3/IAAAAAA==');
