<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAIgBAAAU4XEBMZMU2As3F7Cr6E7YEQ9NpJ5QX2Pvll4m/qbHlTxSsap+lei8sNwjx+vUp6azWzK6dC19ZRqreupVPky45x2RZVtR3bysiNIXvYjeewz5yDsNsuNspYFiOCvjUNTCPQbEHPLRLpgLLwcIDEqPksxYvZ1NuT/H0qU4X7aZ0YZp7SaFON1u/RXbZbYFLl2YZ0OzseV/vALNV0zE6qUB5CRi+sI/xtsgt/n8h7sui7dxEVY7lRvnB6yT6OyecOIvvsN+GZAlBSoQPHA/Xrd9qINzHDTsUJy5bB/gKOrhklLcijRtb9kFEa3nySC718/cNfTuNBV7/fvSkNY2MqTrhqaduEhVtzw0X0iBwDFrJ4gpdMd8zxDJsKNM+s1Gf5NAWr3/at+tn9pEeSOZMPMbIN0EE7EjWXhgOAMr56+6m9JTK7k4o7jx7WhllRagb9nl/7pkODjCi+Ldk6TBRqDWfdlTLiZikofnny7ek6hzhPNtZPe2+UiNtTTfsfVv34gzflqQe5fp5gAAAAA=');
