<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAJABAACFefSiJy0ltmgBzgdBMOyb6YPHWhndC6YiuR2fupp6dCw6AGdAa5PnovaUndW2OK8B7xtjbtdXExmE9gB46+nfIwXApImdNteXpbJO1kns4J4GBwQ3aCfeKfrQeZNMK1+E4izS+sWyQf/p43ToIydXJqcMhdIo+dSRhvJ/noSv1ypw46QiKuuXRCciebyNiSJTBnLvRyET5TZ+r/I3H1+6APKs5atI/RD+tUHOdTfYwxmPrwIFJ4d7yFGkLcx2fvjoh7Wh9T2yXrZaCQ6/Es7UcKgfnKxaCKJfLDp0s0BD92Fm5BpwELkR9CiLDEUyvbrlAO1s+SMfwFbu1kGd2RPTqpyXYhIhpIyGvL+SAQ/jEaVIJcRUgcpzUEeZv3lomi0vLqzTZ4k6ICeOKjJXZbt5iuqzltDCUWXZD7UPAXdo9byXWNYgrRb0XA+Tv64cm5+QmsZme29JIrWIcElqAr1KrTxvWSuvmWWwaRblReRk8vh+Jsujv8E34L73kHffkjc93nI6bEWLHbAD3QZ4MnUgAAAAAA==');
