<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAFACAAB0Fj5FbU2CHS2dlgGTLPFYbmgtToofH7xaotP8Z+WXi58SX18WxyUyYwAyd8L5QAPXEENvoqf/ege8ampq1g7tV+R9XhoPr6rcYmsWkuJJs2Ii2eebjh4Qafg0lQtb/itSy5xuGjBtCnJsHnZHEo7La942/QBZtoAONvhh50nYeUM1l9lcKpPRTtWr3fFyD7cIikt2ZJgPJ8x8V3Wl9l3eEdJeTfVbyvyyoZjwXTMO4a9JmQpO48bKMXL5Gw3RxNZcUG2koIsqNUrqdBs1jRfpTmsqwF6IOb4Ee+3+KFWhcsBM/MrITf1W2cXjfvpZ5xKo6ekVnXEG5n2YfKfTpLYxEcalrokd5ehEEbGOhrNlU42G0hOIKRAWuWH7DaVRJY2bsXp7NPAT/qEp0roHd3VkyiWqcOnqHRsJcFqkONtYLoiaL8EcdL99hhw3DpFOu3oaXQp3w8wR3WA/YbpqHo9WchIpn+EXi5wina0dWXP1uuBsvOu/4L5aUUiwpZXIn8sI6Rinxex+hVyq+mH53AR7VPc8lxezKJoBerVK+r+BiYs0DBWallHjy9yTDHtIJMErP28dLgeqiqb+CsivK3md+o+Vqfpjm/wL7vk/Su2Ck04WXRX253QaJQUNwCDq41jBzu4mtTBJAKI7J42epBo85Vq7yToJB4AxqI/FbstZJeTT1wQfxFyMfntetXdDllXz1wX/JbRC0Wr63eMLCjtEyAE7UePXJ2PcTAvHfAZ9BykZQTGdnH5NlOaMm4wBWQ5JYgd+Ua7u9zTkTOvG16UtAAAAAA==');
