<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAOgBAAC3QDz2W1+5VujtuC74FaScx1WAaNzscZ0O3Ajx7cflzwBIuIuo+j4A68uZ71Os87k4XPG+AUS/3apCSGFvs/g19HRPud4kh6rJfPYDLnsfN7XZzYtL0kkadZstzJh5b3qfYVD4YXJhwxRLmHIDydfAbTLiOzY7/D5aYKIdyVn3ccSWIBrs7JUwCag7ShDo7Aq+lqEcl5pEgyqv/Vwo+zy89uegqUj4dM+E1aK87+aP6sdi1dcewBeVbeYIZzB9K8aW8laVR8mtkVAOMsv5sepHqzJqPOiUAwEbXqe3PFPFGXq8gMwZKF6CyWJveKFR02fsUaYpEDs/pd4bDjGRG8ldNhgDRU6fayZA2SFNXuS2zmPLwwrjg0ENOAaom6fbkAiGrcCxKa5DktmSUHZXodNdxGxZzWt/Sh39VCF8EpliLDHaJ+SaCRt+hVBtQJKKhSnRZBAaE5k8qk57BJy0fcveRmkqKnQVxmwbtnqneZB+kXitbqi3fiBMNdTAQgX4KZHLlAu5qEJMU6lKPPkYDRM4oXEKy3OEieiXXoDklSBVZqj6eTfVQnPF7J5VDMZpBmzfJdZ2e0Y+35LVao2JyQy0bf27r8j3pVPsY82QBtZBBZtV/BstJ0pyPM+ENNbC0xyefI+dmcw1EwAAAAA=');
