<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAGACAACEYGXzvlKRgpgciXtZiVyHxMLpM2VpLj3EyZd29jPJFQta9HTgg6seDlr9Ujb8xxU+fwkvtyHz4qvbiFnjsMYdQ84BwVFMDiTNtLZz6ok9RTXTJQ0rnWItoF6K+frQ3wD8EJfSWywW6Vf2iZaZV15NDlNinrr7nO69rwdvLjuLnXl+P6k6GFJ4TJ4LvhLU65vaTZ3EnFtEB9eZXxHG3MQgZOIgR0RoXwhnFNGhCV6VQPkg13dXyDmZYDcZH+Aijc+j1uPvkJ8+9KySDwuYlyfuCH4aJoqOmtuuLDr4kxnSTVIaUEzejTWNTeUh++utx1INT0ZFvwZgd2wh/IZXMSYS2l7B2TUFU8ppq5bD/dwBOneLJbNR4tvClshY5RgAhHjgiKxcAMzFUwktg5mcbX5sF4IHNPk0Fc/gvi9gR4/yWKMcaohmHQf955xQvfCyjQ9HOz+5xxd3/wO01EFdP7Lhh5Y1vexbahqByjN92bOpqoZ6SUOChT0RUL7h6yv+zc2Rk1/M+apg8I5EFbjdTQgZfqk5hmgKAZiwRFf5Dj40FMOl8vCRgjbydidoRuJusgEEUVxduPYTxBv0avUsFHXz4ILDQIczRC37gK0IZhIqw6zBQC6UGxmu10iv//zOpL8YYJUz7ggiFkUp0vD1bFXdU7/sBUP+B7nGhWlae5RtlGQpUIcg+X1KKcZQOlVE1oHbOV1jy3TpVPA1qAxbVITYzMa0gckSeKnD5QoDCkTageCUFShabNc4w2yaak6qhy6sWhuEozF/gFHwyJVi/7RWKC2ZP1rmhno84z8rUUfqiQAAAAA=');
