<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAEACAAC4NwVfRl8jLrFAOunhbZJSDIEYfsZwMEeNTav37XCzztJ+Yg3A5hncheamUdDZ0U1MoilAr/48Dskj1nWLbh1nudxB7CQXFEHukC8rh+FRqdznut4Z9Jn8v5jY0+nZ3qpGCHmkDZy0R4cHv/Z+/5smqBzVr0/bd6SuPunvVWVNYKfilKGjMLusRMfzzl/W8rP1dJ9/qgnuiM4jTpbn4/hjnqomWcuGQuPSpfV+DoUwi+iXpcTNzXd5KLvlG04a+mdldaxg/ZhUHXUSPMF8135Z6fT0k9exkQF4eXNUYK8EanneYcTBO0J1LqTq6GtqoegXj5YaHoDKXrskXFU2QbCA+5grqbVWM9syyGllTElSKq2J/9e8F5QPDchSscVyney9HMh7bcOaRGhYaADEiocinSsrwHaKeFLV8B/YFVrdqciieuH+CR8p3BrkuiYT9bo1AwHq7Yg+fPCu540V0ISQu0uI7MYrVdMBQcQZ2yzZk7S6a+gD5VHhlNFoSa5DIR7ZGhGEZcITF0i8vtFjJR2RrfRPrm6DTxwuCrvkqhFUqqJJyJg6hO9AcvMya3aoS/cfz88VQDK90+bzNQm5DkaSKvqhjH2lexTkXMkpb7m/pqrFMdqxxWn11+ifDP7pglzv5zg8rt6inGWp7kYL6dV1KkCMLc2dhgZ47/h0aOLBZiUqMNVsHqDIJCsxuzyCddjRY2QdDi3LnkK/SAJvg9w8u/TEMaFe/ivmKlRWUPZVMA2beYArXYwwWMUYI1y8s3AAAAAA');
