<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAEACAACt20vdGErXmiuwYC13liDtqFl0r4sKhxQLlxPTgCPX77cZYRVXLJU8YYpqBD5Bst1ukFpECc7vO9/0RdEGRgz7aQLa2SDFXdPnDWNRjDXDkXkHXQcc3Ff1rDFX4gQpkSg+qIyvDhuvsXJvjdl7ifu3FNHwTZSK0Su1lXIFuwc3GdbQCx1H+f/C2GXe9ABPDAtGeH6eAG8tvzKdv85VL5WvKNZKZjTTbqcQnoB5NbycgpauYU8YnOQ7V2xmtn5aA4k693IbqZ6HXO3TJ+Olhn+3nojZqEzaK6TkO6w9YxXgd70qq4DcNmIjW2vcCqj93MMlF1iEP4CJUdGelXTwBp/5ZnIgChUgWD+urRsXUPaokllQUN7ira9R3YOexlg/8qO/7aqfMKbyrbYl8oHUg8y6X+dW2PhwTwVYMiKKIU3FQK4gINLuIZnBqKAENaGLRZzNZKJm1bGsVjRnX/RLoefPCwQ9oTazvNlStbvJ8kO8bQnFgQe18Uom2ApjKFOnZM4OOR0PmpnRggB+bJNyni31a/r/S0nsfzM5FZmI3Wjh6Xq+odsem1TMqDu4uglZOdSv8cK0HYvfqEL85Xrgoeav5ec61qJaLn67EN6pe9/djAUSb4NdFHu/xQ5ldLCZgPKbLiQggV+bbAHmflRAtzH5h1oBQtcPbilbyn5xCw8WMG7NXtcPgznHsNIml+xqeOx8R+y2dVafrLVW+g0iYGBVkI2XjuoBPxNOLWVJNaatiUwleVpSwMFT3+4jwiM+LmsAAAAA');
