<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAALACAABBTcYGwXN0iQXefd/ab1GzuSroqd2btb07Q6wCWlNcZIqHxx33vQdFOjzJ51ramtpwOjEQTCuL5VhH4ca3M//bYHWqybcZxqh5f1a31dP5DiN+da2+zF9OH29u8lh1i13TVUDv+k7m2aw8gctOMtkuTPgk1ldijMPUle2h7YAyrjf8feJ5xeuYGkJeRlLaOAdlBr37uwakUL3e2tjqOxgacaKXUfQvJwAMVWDQmo+7NqDaxmnx0TS8ha3AVsOxVOOccTilayoKJAx4054VjeZUvpB0/e3R8N8QcQ3N3xcA7+JO5+aBO1loXScpMSD4R6JcfLwtXrYkHs2nDEF5UozqIECkAWJyf7mt6vRTPqDKur3p9skzIG/6JL5IAv00qx5vrEgFGKH3e6K/6TwlcVj1yk+Ctkg0/fQiC6Rsx8JfdSYLA5Y4jiPYQt7UvbN60jkyduF6c/eJTrg9q7UsCmkOFQOWcsbZOqYEdsE0qO0wKQ5aLktqmLIepDCZm98ts7ICcc4GPYTwbu0CPoUoNRnEKLYsrEm7wj62Rs8KN/zJivUJw7Y50SyM4jYpRjiUyNOTuNi1XBONRCKJBS/NKpEhcTkCCqQgoj8Sp8yfQUBzXKjV8oNIG5gvwmMrp/T+Du7cmfPVUs3aUlA++dE9UhcW9xGTAFNgEl9nv2dP5aIxEPhuQ+vUyOD3EYp7n5cK2dXLnfdKj3aQnDHiuFkU4TvqlMudMKs7JFJSiTBlHLoMeJecJ5CZQgQBDqJgSRqDTx5LYeNIzD12OQHyXT0qnlzaZtuhBRajYLdaCkrGJXCyUFbm/mOJG4ADPNhOHlDsfmeuuDrArZX0eKfxpIIgMuowWkiFOoU3WNlJaZbxlyKIlEXXTkM45b4EWINc79cS0FMdEaN3AYcvI+Rk9RaqcnfqAAAAAA==');
