<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAHACAABfdWeea1f/2AXar2rs4XiSpDSON35V7WkjJIAFv7BeepTDokEKuCI4Db6nIwSYNrLUtxJZ1BkWdJpkNOI99nsP4n8pwtjINczyFNOMbxGsSkdDqw6bdYTgzdiVKeG3+NIgWtU353unDsW5+dtrllJXUy9iKFrQC8dAGM0hcm810w2RlZvgT+XjOan0Eet/k070L+VuqzyAwGiQvO8Kn6zTh8OfT0Sr4N4HIlc2v3x0BySM3U3CwsSiEdW2g/N0ajNj4tzTWHF6ux4O6Dow0k9aAw2PPFfwVtu7TzaAJ3ObLMFC7IsGLWYy+LnYueSrjbs8xXEtMgFKnpCMZi2SPrFdmsd1Yr7dbHI+IUuFNHSKfq+6HrsYH11FZHe8mRO/fAGdVjAhvxFDeXoXc1ctXMnM/7DXfVMfbsdQZQ412xT+oji+OrSYsP/aiKy+0RDzOUQIV1QmdK0Frh5Jhoowzh63QxXHYE1n2aPR1SaWtPWLDsQU2xPbkvXZjeOZy1MKmCY77XBcDOJtAkJnNW/1bernbhniQnaXqpChjunltSlfXq1js7i3xsYX8agCNkkmjPNhLyIEhOHiuWrFDyh5QITlCEoDi/X6n8ZsUdy1r7jy9/vNOWoQ+0oLD5xBmfIMrxHnxhgE1EjMv31bAbqQ9bcgK8H6C6J4A6UhE1EkAK1Vk+oYGmMTRvvrtPCYiq14xpqHc4U/Lp3p8Mh19h/pb4iAyMYvmjE2M+h1v8KjoXSOqbVNcA+wmDjqZIIfoouKjJYLcQJMjw3K4ya+q/ScOR8txuJQjAx8FvHHs4kCULidbTdSNPdf+2WsoD/7RunpqPcAAAAA');
