<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAEACAAAWISLT1FbiJuaumpRZ0L8oDLWcMz0lWUd7vMWFrnrZpuqQwisjdbUhdY7rmVi+oYWFBvJQUwIrGICfgJEUG5qZVeS9I+mfa/zENErOkn3rRohce6sQNS+pVQLrY9Xv3wLH1P73woEJSwlaN+LtcrdhMFfoDwa7VM56JAhLc+yZSf9RKIWmx94xEmA6Y4qdGVGX1/zx8ENfvVcCxzd7JqEWPJHqoKV411hK3zFcyOO0GTWShx6mz+7Zgvd16lq1aSpekyIb0M18KaiKfwYyeTD7tsMqsIMQcn/oiJFxjdRHZxlG8dajks2xKuiRSuOlql9G/jattuj1a+bhyQCIqW0ITbePEByJ/iXnw47DJx6/WG3oGuw9kzeJI0t3Vy/VjWSqxze0ayJWgpH6KyD0tDWYMMiHO1rEDGKncj3EwphCJTa+M2HEqTqRUbGndSpxa6/OlzONlKSmoZX+SMY8gUkEGuGvZ+Y6d6UEQYWQZ0YW5XHf9ukBGeLebXehe59HSAFucmZzJeQXhSNaGPzDsj4BN1XEGBjrTspZeELcDqwg3SeD/EtO52VBsLzX8FGdc/LcbZTswSB6C8YwP+Tkf7xiXQ1bgwczh/zgZCQ0gwp3CZaZIJ+6zMF1u9Rsg+jf/VRsI9PAPkoPbJZ4t+Oue9OqtPJY+cPUkJLVsj3eZUZCX2ImXV7CqVjIimZ69pBBaNAl2YRAPSk5IzerrJJLrPqEhAHEYLeZj5vRix4BpkJXjFXGiWlhnz9N9DxuxW8UI2kAAAAA');
