<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAACgCAACAl5ddcPYA2+Up3FvYj7KUnUoimwjP+K/qxy4RW7Uz+yf/1D+xrhQhYvr0AKjsbYBFHiqmT2mvEYqAO37BcnZX3FxZT4lQBcZ512rCpcM4dFxymbflNQwc0T04jkuMKQTCg7BO6DG1LoC+rNBT15+IG4wp12m/Jpx6y6HZUaXHuNWTkbvMhAePTnf2XPqIVFc5OtIhG0DgWhnkfTTia1QMRf+Vvw5H+mfkfLZrNwbwirwe7XR7iI+oWkzu920+3YzvUgzznA+hbVrqzdk36RUrhsACqFPumzXKneBxzyAu+jE6/teGn9o4Vowys4cmXRzPoej3+vBmEGxwzmm134t30bOEcc5ScETrnRBI0alHxRngnBc1Z71/6nlHU7Vc+9vqduXatEIHApNO23QF21Tcc49qY3f8On1Cn8WwSX0laRx/xnubuBRzjkId1vGAkMfzCwpIPDAsYd+Ka+BbcBoShUwg7KDdKdjrBZmcJ8NHqt69qMdWM48nM34waPIrhzi3leUC7SiQ7SoiI0Tj/PAWzeESiiUHmTfJKof3d0+HckOYIFbxVPZpnKjxTWwWAcqGno7KTwSRUbYecTQ9n25j64lcbBpeoOXAnH7XsAUnO910ps7amQcol+nPqRxjRrPbj186o51Ba6dxodzwEsCLPPaSQCNolMvHC6t0JUcB0s+t0v+KOtwo5hTxrdXCM+XewsEUZl8kzCy0DLr85opAERQqNh2s1VIAAAAA');
