<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAAgCAABTfoO1ppgrSDdxDUnCaTxkpk7lw1mlkAcyUcXOvK5zvpJB0vdrcJkkPQOmSzMTJEUkjSirtqSrkxyx9j3BgQfF2q3SPIe75k14LHyXTlrUNTMKICQDMUuhWSMM4P3xNRc46ZzwVHDWr9n+zHr8T7ndKj9dClh2l60qbd44b/IIx8GkjsqGAAYRWa2ZBA7SwXUPX3EnXihykHFV4dpDtks51mDNOkvOjf1zOeWbBpmuAfba8EiZ1btuP/Sj3NDRWPQvboc7cU5A8BlighvdllasSo7B8lf4M2EnK2Z5BPzGu4R2EgMbPvIFtQl40EcPIOAu2eyYYss8kcDTTjrp3YFhazM3CmA75dYi+rgnbplmQBf7Mj5rzUTJK6t+V3tbFSg8ZDGhQlbfKz9TyPNXC+PAHjDBgiFiBFLokpF/Sf1gODjGoPsHGURRSlIGEO95ekxBXQeta42VB+J5nTmo8Riz1iUS5fc7IoJ+bitRnLbvNGHrCI73z8nbim6iMHR1pLlmEYtcktnKreHM73sCAPJ86xe84SBHxsmLkqZoSUoAMNr7q6WwqgzclkBj15sPiSrGHUb+NBa5YksF/sS5AfFgZ1kHrX9GCMZr5DYqaTqpkvIO9KlCbqQZkle/No60jSuR/JNAJjApZ8pLgvW5+BeJ3ScukYUDZ/VAbrNqJSZcfBUs+okUZ+9FAAAAAA==');
