<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAAgCAAAJ65cchOqEEPLFS3qoWZ0epYHcyxLk8fG+wCxBtcPxGP+AuqbghkasRSaJRzQ60gB5WAFH0K6bGYAdTccPoStem6fFHPzzFzkvwfAJl0OEV06v2eBvCsriZYpt452nZlCqAhLPnmkxZP+ofwiy5vBFQK0WGJEfyNLZEA3T3cMJKpnXBIg+ukqEPJSvRVLSDNLnjpMkHn0HdeovE2DxlEqHCq76mGsGG2Mvtk4rW6/dh8Ad1p9mniPBrPOZLALvq29vmI4KW4umtbmeVFgqGWIYBeSXkdvONUK/iZDn9RZD1fgx+qTpnwSDDW85YqZ9+9zN+JHFNQO+SKTEuR91boNYCAvcWYlMYViCd3ef3r40iyt+89W6W/pRjRrzPXud55bN1VzJ+lU0Qz/1DXzTgt5vWcQw9LCS0TSp5uHsz8ZQMR7ytt36WHPF0Qe8ixmVMDTVHX+yMd3Yepm0spErdNceXpFwQMbYfGkYKC6evDdQluJttte5JTZnjMzVSlyJRf7Ra3JscSMACWT0cuivZRtfVkbp9iH1gTbV6J5Fw9PocyBmLfwml+6FlS7/ZjxR5EKyLkwh9mY25b9e8gCt6GWg1+nvZNQ9JM70TdJFRn4lNsLtQiPT7fFkKNNyOQSFRde6zzVtsP8a1S2eIpiYlrqbZwQAF2cEzqN7d2wHO+T/z+uHbpUkZCWBAAAAAA==');
