<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAACgBAABsj7Jf2Cbb9nGIJHP8VSGrRJ3k9El7ZQgS72fXrwm/s0AjTxXginY/wVxsDAe2IKUhlAqIiFpbucPXMuvqU8wXPOnvLwTKy+y4Z/uDtcFtQQF4e+11gpwZoz3SOBrKWQNVE+6308X1ezmYLJTtMgBxXpmmrG7YrBGiKH7++qbzsMwtjCQdB4AFgAsS8Gj2RaCQ2cH6UlqOKivLTa08EYLw/ghqOD2mWXbiUkgu4fcmn4wKa+x2wKfA7X7h4YnZBQF3hAZEC54bvf2Wj6uACuEWPuyAz0sYmoY2kk+4doMVlLqz91RguLiZLWlD6pIMeQnYy6klbqK0uCyChGu/YeVBj9dxxdguDqHQKOVfCQJVRC9fgBsTsPDHBNOhYQ7d0fFpIi3xvGjA2QAAAAA=');
