<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAACgBAACmUF/eEjQJLQdWHL6M9YGmPjecgh+OfsYMKk3bU07OYunLvOSLGdZq/Hvhp5BPzlu4nCVaT9UjHDEr/P6M/F9je7nKWy2hXSjoSu1BmVG+SGEFzbE7J3RAt6LGi0yoD33F7aFX30d99rXQUo7MY37bQa7Hj3bg7HCtUG9aW21cHRZoNFaKvxeeQudw2cj6ayYEsrg8TyiWH08L5e0k4htiety8stC5ou2OIevtjVBHg5s7tAWj15kcJEQQMgIvqCxpGRMymZ2CfYJXHfAnPBOYL7ODvmX/FYHcNpkDSPvDmSwla3fZeReK4YwnjGIm7LTE8fn3NCTebNG4gwj3qOYiZex+NYgQ7rgM9ZIb9+hrZ3xewCtzPpxm2ZYjWzCrZpj/wk26HFMp6gAAAAA=');
