<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAAPABAAB2pc1kGQxhybKOoBFZy9ZeGqbEoNsU5brIZ8slBrQElhwujQboOr1tcqNmgjyFIV2juNbh+HVi/vkx3d9+/SWRxB/CdxgawQv23pSqU+9SXBI0dzxlTxkBK6ID6SgbDbn+jw1dXJJGgydnMLPcvK9ptxUnqDJlOtuIS6/yiIbDm0dTq87RQDYZvM/jGXnu0BspxlNqihcZ7c2fSXvcdqldqTdlan4wZNHHRIVJVuNuW8wVsGkJSpfGEa+Zu3rpkF04PiHy3Oe2aCCWGwTvF1pZ4FGj699MwYTNeNcdBNTt2jr/OqRvK/eq9VAj4tVp7ZqaqdwxUpriLYncUFLLeXDMfyNYzACc7USKLM/Yc1w6r4C1HjbRLT2G9lEUzmKNlXKt/EFBr+ZMeN3JUn9aGESKw4AD18tVlcVdAAqb7d0gUByGjKQByZXNVCYanLd/kOPBf5oY6T2vlYHcHymV5IXzHdZKtFn2mri5WUv4OGJopWFlXyBKXNPjPcwl9fqok1jRp6363f5JxR/nBQPGNPafNl+DrCv2GnlrT2dFVsjXYAYvOWRWHk2QaIQpWm8t1PZohcXKBw/LEXh3YAtg1IOAw5Wp7yk9Nh0A2T4hZeEWFYcQtMveTMhEHzvyReLz/knS5iiegbGrpIln6xZ2isyzAAAAAA==');
