<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/Nnvcz3RG/S3jOHq/mCiK5GJh37Dd9sAHK2mQ4XXU4mmITLsiYFGWEqaTfW5mYt1r7K59A4NzPdA564Wn4KooO6sdpMCEFz3N/kP89GPYL9Er8MapCJjP6dA5lRqJBEGdg1dF364CVUwNE8WWvcQBiUawnxG0ifnbvhqBM4yJZnInlPdB6+bKsSeupnLrGDKFUQAAAOgBAABfMTZnh2ABdcPLnQbueVo0LXlxjxGBoQWPVxrhasUp1FvZrRwgOHyUA/Sde6fDaPdz+uQdAIufo33c7nzcz2hbmzQTd6g6p93y3EiSkTa3Jq1Tgrt8juK1/bD+4KKWH5vic7lN1dZ70HTCdbxE8Hxdv0Wb9oSifgSZdUliJbHfUjZoVTKL/IwcJEgqDeuXcmZkbegkhRDr7p/etv+OQhrTZ11jKH7dJvxI+sWBSu9BqgUxbOO/o8Dee0oYmTBO3eToVyA4zc6zWO0ZGu/W3pPLid1bYDR+vL0hsUbWjISUTM5zhuSJaVsM+8UQuEQ/Hwvreux1PH7WpAz5gEvWu7UFmQS/utE+mS39FZr6LSEe9RRrvfN31UisS65pidsZnIm1GkZySQq3mWgXwdUudqZ386GtdaKehaiwJZyOB7l3YQdCDajKouimw26le9ste5qa0hPzGZikSOoLk+ojxzB8qw3VvmnHgqDmC1TQhnUjpUCyQDsPnXmEzyl7JSWOdyRERCzy8Vw6jy5nttCcy8fgSc3oLvmLtfvyKegJvZoDUYXQ+xVNKo7YOupcASzj0K4VJjjiXQ3/GWsj07JNF3OSoQrtMXSkzE/JAvPDuzG/WHWm6l2CjMD1PF7KOuaVOFt6F7rxProoKgAAAAA=');
