<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAALABAADd6sCRKCGqTQJCvaTP0XDpSx4k9z7MiAlDSH6xzqtXNdABrl8K9Hvp4vqGMZsTqih315e95TdTRK7Hwpw0JDHiT/Ke+qNG3acxO+W4euq7HKNQiS3P4LauknqdY2tZEQ0vhdWwRONBkbSbj20T2ZhGKqp+zRFGpXkk5j4AJzwUlw75IRl77V7z7cu6E07/EeSceCRhNWZoosoHGTwGRVy5/k1MI7DO6bT0uEruC+V5ae6FCPXwp8Lc/vzkHbkNS/KoHaGTdJ9PUzhXnoosC5wBsUhS0lB5STWBtyd2oQqqaFhkcWfw6GuE+6cruvhOVBEF4PQoD3zi949r+QgQVDk3n8KlGEBr6sWDQTtoMvi9xkHNm/n0ZJPxOB/cG2dqidkZ0qNdYKJJPCd4NEo3RxzYYX5t8CF6skyVg0+vAgkTcrKDnuiooR07fqNtp2m5TQzi4ZvSGtYpnB/YhCw4snvPmG7+e8WJtgowcXH5G4ZwDzJRzQrN7XrXRDP3AuhVZI+ICMDse4cb3FJjID2KBS+5bETMNUG3Hgp9VXClcsn6OpvkBEscTYSU46+otXOy/KMAAAAA');
