<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAHABAAAxCcItAQ+lOL7APM67UPI0yMm8r/DBs6CbeuEPGQnLQstz23AZimn5EMTH0y1Gq9Y7Z8mDTJbO+yjoH6A51KyumizZiQDooGuwovGx0/I/g4XDFq8rSiaY22d469HuC66hziRhVHYCfLUWx9cKi2CD1Fked9JTXGmq4o7mLfWLNT+J1wGBMLHOPODTiOM8eX7f1rFC+iN2bKHffffFhEwjJd/r8u4aEbFkJ4GNS4tKlhScoEDn1aYkcSn8k6aqSAa/GyDbyMZuev/CYimBJ51dyVjSSDEVmMdATTI9jRQmxJF7O17tsj835sff/SwuvBD4AWJ35KWzUfM7xTNQwlCi+kPMeZshkl1Jcnso8ULhAgTJTtyjpt4Gr1jUpkg7rhLYQsJXKBi/7C7HcSyIQ5VEK55wdn1d5qGPV6KzRuSyeAi1Lbu8zipHWHMtcvcOqPvw1CRbldxkb4bwEkcF2W34kT1R8XvCUG9tFyrxfd6AIAAAAAA=');
