<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAAHABAADaJXWUIrcRfSUPcaeF4IQSZ6i/SgOS0OX+PFZAG0sRU+BozxHxJZMnCl3qpSU4P8MTMBjk2Ttw5Tom7QdaxMRFlokD8xN7UR8ONJ+QHbSvvghRPPvYpeDm79tnlonv74Uv4lhOh3GmZySJk3T65BVzEA4wtUEMKm+XVNyo/HM4kDoFoKkU0pdr8e715R9hosp92FMYh12NVbn235mopftMglQwXL4X6ETnCKoMjl3wy0RkemS6CarzfoqecanU4WvsK6zGga5mjKQ+pNKWWbmqGPOloi4gHe97fBWbPcrCMtTVp5BXyoWu1SJlElKEkyGuKH8Xm9ZECMABQLZ+MBLhWS8dz8RRiA6umzCzrNm4V6qeAszvhYeVOTN/+p79Zrox5GHP6r4Xa3r3QCB7DoREquAjj2jHVRKJJaxwHrQCkAP1IjyHxh2RbmWCxgLwV4DImzICQ4xk9vwAlFiYJIzAkA4BEtygMj3DiVDAbhPTXAAAAAA=');
