<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAADACAACzRTtWKR6uDtrSl+0epq00iT12c3G9/p6ezuo6pTQsI5C45x0BIHmoJb4RWVHqLQB53OPqN+o/dDoZifFCPTkdfKprk3tdrycv/GQ3jKbK6M1vFYsV8lWkpFcQQwnDthUe34XcOOS9G5cOw1no4Pw/hfL3sWLHiRg1U2McObBlk2hboPoXGKE3dneICEKMRdz2iS/775i2sL0uUu3sWk/e77OsvLLCSW0TGiyyf+CFM9u2oCCdfoNDgFSuggZTRj8feQC2YuKy/w8yc6hLLdMt5ctzxJo+0UjeNWv9BgeIBCAEhgLJZDFdqzvyCzXEEVi48frsuZczMrtiGQxtKxHvzJYgSk7kX/SZV5yeYGVY1XX19btxj0qQqHiiyp6KopIfUNrO7lyG2aYNU+Ir4XCGeU3C4oj/ILEMhw/kPa4HiufOlF6HWIGgH2wVlyweCxuCIr79qB11GjPkXwIEfVMeJv/805dxgeYvoXEXUzZe/6Swoao2OBLqXAkBLivqmz+3EV8dqYIhhux2RZgj3p/W+ZEWavjPSFisLIutoJ0MAiHc2s1oCR6vXXabzJHttLoOrur4KFmECWUDpBgJKEcOR9lZyppH4VgbqH9dwhql+q4Z8VMZGQl0rRS3Ix0FwDzCxNmLjbuZ2ScVuBZJhrung2ViJpXtiuHmivAwdR28TA/T3VuVLmpUQDWdEkS+tz0pOzMpzsb9+Gn0m2Wjca2RlbmTmHm2bFcY+IyL+GyutQAAAAA=');
