<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/sqGiWsYilci4TODbatDixIv/bFvWdMSezxAUJXq3u2Wz3172Tze56vEONeBV4fL29ETJSFElro/0qYmxQm7eU05tlqRZ9mO6rnqzb7ZovE4h46lYycJGaf8yDME0W7gFwGqHdBUNJH5ZqVO/gK3w1sP0Mk/Z+lcQvnsdwFJNdkfVAn7SnMoKEwG6ug6xl6QVUQAAAFgBAAD6gHC/GMF3BTulTEvo+DPs1d87/RbjM2slogUDMVydvIf9Rr64HTGV5UU8geanV4o5MtemYUt//GOspl1VX9BXMZvHPRtJ8e2m3KYulw9MT6bDouqBmSnjbEp8MNa26+eDnLm/0EMbwHbZfR5GcZhLWBnobMAltmBAU8VqivVzR8Oa6TZlRe0gLFJuDC7kpjA8GuaGRLLy7FnYRyAz6oZQcQCx7KZQUPscrtw6xd8OW1iXM1VlTkUM5Zk6JYkBx2PW+s9uBogFJi/zKB2gRc99P5iUWXjrKfZYMHpw50ESQZoWvQBBCC3eI/JGNLJQHlGVn1XsyuTKqESK49OAwsXMPwK4EgmUfP8kAd4jBupWMxXLW4Wbw2aE9VmFX/I8yjltFLAf61rLwYMsiEF+iWWgGT81gHy7FP+YAEkhIoXbwx5FIgvAtfPUO8CvyeChZ4wVmEjXBuRrZAAAAAA=');
