<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAFgBAACqwj/acJ3MGFyYVSZ7iWvRgKuXZ+u828+efPeKtrTdUgdndx8BILwQFDmtiaFLoJ88KT9Y81p//GsgT4UfGpTeolbvw0a6zG1zR6LJGM97Go8Yr0g+dovc419WwzrnUAe9KSys1vgz9FXWEV8lETEj4WM3968szl0JWAZ0YaMZhoSwLGU/IbqgGP3xkoHy7GcY3ZRagBuCtRUBcX1I79HV+NnTJF/l0NP/nldWqKjD8n8N5YGigoiV2io8J9pL2m7hfaj44bAREwwfFqb4K991TjYCKeMAjPQhnNWwim5KRXG5RQle2Jh2iSFs3MGv8N3y+OYYULuEsbcu5khUloMrNnH6TcbPBiPj0uMIOgtOS1iLynoid2f/4molGNncv8BxeXzK2+8bBtDSBtT+4EHM6jDOYzPIbTAH5ZlDoIvpopsjijr9Umaw2Km/BtWkTuU1KxBh6Wi4LwAAAAA=');
