<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/sqGiWsYilci4TODbatDixIv/bFvWdMSezxAUJXq3u2Wz3172Tze56vEONeBV4fL29ETJSFElro/0qYmxQm7eU05tlqRZ9mO6rnqzb7ZovE4h46lYycJGaf8yDME0W7gFwGqHdBUNJH5ZqVO/gK3w1sP0Mk/Z+lcQvnsdwFJNdkfVAn7SnMoKEwG6ug6xl6QVUQAAAFABAABsGfx30ftcVjXL0xrVa0DE+ATy/BPsFQvA2IJuaZ/FCTy6ax7OxXTZAkHJuPNT4BIVdSZKyjZc3X2+SEOq+w5DRlimX/Fp55LHin38aTMlTx+kcfEY7XWEybJQyu+0cij3AjMXDsLQ4vgMb+vRr3dQQrnpPhLkyAYkE9h87u9CPkZWJNm0faPzv1sAz4M1SQiUgPh1MQXvlu5I/6BeivszjD/gUJ6kWRGYvaQrm1+8c2Uq+E8XQfZGOshKPmfllNPBNYaOSykrjLHUd+ciH0Voz5/gXfA1iUoMYNis1TWdyDWOpGRN/xGUlkPPaDlPx0zmBmWfQ6G1krSMoJP4zfZ4HGrdxZF7cvTMb0aL0KGHQMwxcTDsMkLw6UjTc5Nup1rzV/umjQ2nTvH6Enas5H7ULx/Rf6foMoKviKedYWYocEppXVv91fVBbhgsI0FWeS8AAAAA');
