<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/VEBYUb3N5SWUerWEHy60G0ySZz74h9MnOsJWEkkBtkjQKAUTcu77IyGp+y19OrOHEW7qZEWGI448weIFOEl/u2ERbo9Z9HQ9hi8gqnbvUM7/lO6YvSArHW2yCcRaxVHxe7/dqYPwkzKvPDcVGbj6SM9htAZukjTk51RnkYmQLFcI1n7l/tg86vSLd89myxDlUQAAAFABAACT97vxvaQ/cW5/kj6qw+QO3oTbDDvLZRxA0Gw4eJHirzpM+NuuH/h2VrzmP4AiOJmoM3BHgGENNODhByX30xi8PSYWU3lHLKcAemsQGNRLpPshyyUdLKI4AxtGVrA7oXUw7avDGN+yFWoVvhXHjdnNPLng3YgWtoy33JBZx/MmdqFJ4NnCow4W9kyKxZMPHLWxv10fP6vYN/jyALO+FMm0kQIPyAJ7mUFi908eUe301UHLJsqONpaDLCrSJeHYzA4LrCsXwYgT/hF7mbNS/sn04B+UPcCmAd3Hvt2RY8oc9XLiI5dIYPFr4ppfCvu2/24I6XvAzrmncTuu//i7CnpcGirXPqCMPswWCHKxIj5VQlvw6bQDVeF3riQds6qTJPb2lvMW+layvxAICeTiQ3cJ5zXNEt1FulH2ylvJ/PeVUBZhuPYRQ4Uq1CYKwJpp4sAAAAAA');
