<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAFABAABFDq1zG042+7eqx3w+5pY9Ga/aoJxFe+woBMerDvIzTUhyW/nitgWhTyno4UrCpx+ytLP9vxKnPc261zoAx2sxVDpER0c+RAvDKDzXracUMsH9MWlsJ/+scsV1qmRPgkF8i6V+e7ErgXNJBP/e/nkYzJplgkeyqQ5Gp6mRtGCCcPVCdLw5+iiAVY6FbcoK4OK+w3kZ7ehwZvR+GSpJ4MEZbxi7xbbD4UfdM3c6DLhrFudvb8i8W2j6fgEgi0ljxd4WS64c4P9npcEJHZcSJKj4GH/72bGysiWD3yO3fbcmSuWsJUM7ecsaGVyqB/jA9fiuRto8l0OJKyOy9RDQCz7jhzgQFMwWA1OF2BfcNDh1vhEdodrvfflhw7EGVLDaZojFhcmeBpziFnc8jYfFucZRi+3gRRGEnCtebt2VrPLhSA3Rqoqmm1raUldFmXgJduQAAAAA');
