<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAIABAABIzwVUOJHe+ISFLW3T6orhh+VpoY0RsClqzw9YARwyVmRobrjYYFa8XMfV63gESrFBn0uiki56yGuGrBemk6/IN5wkgy1wwakXOI8EZ+pbmiNBA8hro+yzmg5S1bzkDIPB05P1ETdsmXBi7xO2L63n7uGAXsS1/1KF8sohZyohkd0zMxxEBd/Z2fdzj7dWvOjKlhcOfT9KkPCYzZ5pGSjqfkHciX2XtKCm/WAkeFjSn+h6bwlnoKIfxw6z2Sp/nDtV+W384IjmM2D5HpSU4/60+Ueitf1BlmXpIjCeHqSi1otzGtadX+/sBuJA/fcgykFBEiu1mv7lxsu7Jd20Z4bnVHrUBumsRcStlpQ4pGbhVBsMXGD+j4zxcIWv25BPAg2KtxxQB3GWQV/R2eTy+n/K3V3ylvdQW/2kYeotSgUw799wGjpKS/4ha0GM2FP0RycRfUGIrCU+LHH6mX/f1AsMCbH3n/dZWjS6jdR6GXQ90oVZl5StMVNbUG0/2S3LxAgAAAAA');
