<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAALgBAAArbJTnpjPizIzJaSgxMZoMsmslTmioNqytQlYkyGAjT9kLNnzHdv442x1gPARsLEqhop46vdWV+FPrkA/f0fxe5LLUW4l+i4gQ96o0KbzmF532rEsNME7IGoG0mkVVVCtQTnm8si8Z9FM08kJV8K/Zc9/A5TULQ2EELKH3Q77KX3IZ33WxLwh21Lx6zNWpWp4PJgdbHx3/QfEnsg/XxxK8rgCYyDZm6wQUOjQ9eGwhyeTparX/TtlIL80sdsWkKt5jlofALWjoQllqh2bCfbTWw6UvchdpFw6JCfE83PjgZcGmB8meNaXFtmWZYIXnvxq/n2k1NllGdL6bGFe+Mpt35XiBmnFhTxVHkuWdU2X7r8gbeXBPR5iVhkhHN3fbcPLm6hsCCwddt7IUVAZQZhp80+FWnN7FSU3olbuBE3oIc2z+9BAv++FPnFdX2WogrciTN88u0ui7SuB0qJP4Gj0B6cSe8qfLCzBfOYK8pbmNXhXhtZxx2BzFrZLZKA3VsNBUajtu3kBwmlcWGKrOs9GmOEMncdXvEb7JnHyVWHfkR6E2nm8drYFYypHoUY7fhk8imMvDpnXVcwAAAAA=');
