<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAALgBAADtUVLB+hY1JOTnhBUkb2vcnLi6Fh1MIOUPIegEnHiIV8f/KniSqvMLw/rDHn4sm4nBwiaVWWHh9NvYtDf1/VCMTqajHYEROpwACqGulsPZrKW5RD2QRcyTyCy4qfriHZ/0C45m9mA8fCeXGwzbK/IH5M/YJcJdBJpxstChherDWibQazsYPXr2k3ue4NIjhNfieYatpGum5EuCkAUrISUEUkqqk+Q6MRNX1lDc7UJBAXvetUnYMWEMgkRH2veiYDPyuC9T/TVw0jcSTzb/+RAXixzT44LN2kIYOwNn6DMhx2k8v9VDnIeaDSWfP7bepkT0qFgmn6iPOMSGPKkWazi/EO1G0AM7TEdt4CkO5yO2USv3Ur6UYnFhNoRTLQMC/MAU17325uyw5NYAxEZ8Ckviv7SPM9EOgiY2TIMYuPu5MSXMOIafCXuRJf8E3QopBYmiUbbkWxu9ihhkp5JpAQzV6YVhk9H5LJDB/am8X6/xsLFrkgVsVg3J87VS6bd+nqD5sA6HP04Ucq3UJByAfzftpCueLF1GR0tI9yqu5wr8YVIp+oWAG29E181GMNFeCvvB+hY6cLe2rgAAAAA=');
