<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAAHgBAAAJzQs3KnuHA6ycpvJBUGIG/DvsAi6a+nKClrMzn9e4VddLuzWONVz+CHYow3VAiP5MlLHxdpTpvxci6swVNrLlyzQXoaFnjiTZC99eokzkK5xYXwNPJ4/bmbRBBZkSmvSCMjmVtLWCZ1XqbMUh51wklJDwZIB6GuIb9yYXKv1IqJAROjX0jNaQW2hEpet1AgcI/RdQF91K9iue6tZf1kHV6TEMZOAeYYIe4izRcahhLhLCZkYob4Dn1N3bLkiSLA9HNVq1njnSemdF15ZsvWB62+1kHFBuZc8alZW8c0JyTyD+DPgcy70I4g7zo+PDguzpmuduU1FJ/dOCKRf0i/URGlx81bEGsf5Ab0kBMol6WLjj4tcSf1m+UyhdQS5YDASVeq8a9fBFfhicuWecnUqBIb86Jy1XTwiHhEF0rPPL552abynleDHaNq2DFMGEs8eb/ufONNKP23I3gFRwPgqN3oZ7uHBOlH2FzKLYORn/mgcqca+RN/+GAAAAAA==');
