<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAACgCAAAWV4fUF8TRulLM3AaNcTewT0uZkUNDyeHjysDmEcblRpDVU1gRNyFAeMEoREvv52LNTw6/VjrKb48GjqdyWtMJwAQTNh5yDMoUSLXs4CPJlw3Es3ZDRGGxBcMttvz/dG/CKJrXQDq3M0Gzx1BU4Echtxie+P2/1PSKUbcVCbOd1tsR58oQaMZV/4EXPerqobNc60ADpjO6kqYC/zfA3KjywTUIM5HC+Fwfek/ymbIVH3C5KDlzyHrfz5Z2wERa7hs6Gx7pamauJqV81/mSxrhvqgfrxx0hik/fY1kZqJLr2GpY/6Va5UrV+3Sk1LuUYrMqKR8vwTSVO7i3mUD2Q9SJ5F075ZYnaqLfmBiJDSL5ZYelQiDC+XHxNNOZc3VBmr4dbGoU5tLIsWTi5OtWvrBCYS/AXexGxr59UTnDfVZ7uBpOFaxBMydHzMzQNBkTSBUavdarwP1tbUfBroXTJjJ0XmwXCJobmoRByDcwDmU3CyfNQ8hb2JoyPOrlAyOlGAbaizPlNN+6XytqM4++3Ai0hHceFhgydyJfesJ2nmyRndNnTRJVbMLp0OGibOA7bogkLYVpR2BFpK0+bZuJDI4zndnAgx8FOaLGnasamLtoolpBv0YdvBHjFl+UJbitSHDgNAILm9NrTJHPSnXblsDIoIuWKm02jwr1lcfZpk7b7dRsb974tZzE3egYkIMOb259HjNVzRLpIw6l31uNrL3fNjhRVlETwLIAAAAA');
