<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAACACAACFMZwUzIdC6gUFE8X3M+D6/8Z5z1p2RvKReTsOc7AIiUdRSYthdOs6pkMw4TB7XViIUCXkaQ+F2Emgs4H4LS3Opo9xJNm+ySdFiSSVEMOYRHyc5tU8fLSVzoAUc5vmSttoa8iJqZygILYmD2XKfaNM/VW5GGWLEYoYTaJnOy0SallXOSosWbf8+RGvhVi2fOMtUmh1DR6NihtlSkA/pqJ5vzfGiJKVfRQpVTveteM6PqTiLLEhO9tS/RyvbTvOWWqbpCaCjJETwtxvNU+LtTjWEkEOLpa8oG4Qd/GpGM/Ml6TfsWEpBd0xdLkxLGJRGoGs1YpM8BnaKMGGXloq9B3cfjUSXMdwLDNt8aQC3zTtUJpYRuMq7990CBOSXQuWhRtHFkwewd0mtA+QQ/NLeYtBq2umriMUHHnmPb4JBFzaWSTnjcHXgVRnUJLHsmGZSMMQ3R5VvjWYkCx2dFK7oMPHQ1c5e5I3ysepEnCUFxLHUoYYeDQT+luwgMxm+TYOqMY21u/9awbYsFtphjnanswa9oQ2IliBZylR4KS1ou2YcxJB2v9KqP6Pf9Iog3dR1Ok0P5IENH0tEVH0Xy231oriibrGvUj1FZnjIS25OyC99VB8HHN4ZSHziTk223NirmcKhoLQ4tUmK9OH+cJJeFnBSZIV30SUbkbD9ZRjjzZZLefOBlfQvWaAMZB+9E0WkFb6e6FLyjyn8xb1WmS8Q9seAAAAAA==');
