<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/sqGiWsYilci4TODbatDixIv/bFvWdMSezxAUJXq3u2Wz3172Tze56vEONeBV4fL29ETJSFElro/0qYmxQm7eU05tlqRZ9mO6rnqzb7ZovE4h46lYycJGaf8yDME0W7gFwGqHdBUNJH5ZqVO/gK3w1sP0Mk/Z+lcQvnsdwFJNdkfVAn7SnMoKEwG6ug6xl6QVUQAAAAACAACI+LJe+lv4ZwEEvJAKjdRvNOFlW34VYustM5BsQYiA6voEwbet1Ge5ahS/+vUneR42VToM6n9gLFVlNI+MwaAA6gNLcGAZSXDIu/7QvhKQ0BAHlmFFAbFiZNj8WB05a20ZKIfxDZtvnNfazZTPU29AyykZwgNfmPYxLALOg99kaWPCqr34MyHUrbuM8yNGOoSo3sGQclFkziywvuwi7Az6lyTUJtwK0axCoFcd5coNU3i3Hes4+SIXQGgZ/SlZHQVNKwRfJA73126Ru0kmk/ygeX1TWskroyLOsph0cAV4FNgXMle/gpdX28voKTxPLqzLqPTRKPhQLCFWoaefqtsMl/6MjbWAx/OqOW5449xmsKbieFeoShPaS6tmhvimlZUSddpKzPu5s1B1H3W+DCliyuVha+bgB0UYPgDEhV/mWAp5EMlNWfJoEuHZxNHsez0f90VOVF2mE77RymeTuSVtUWvEx0eJImyVUchVP/pwELMjxxSaACCQrJ7vuXwCyxlZqJJmsfoMHY/BLcB/ARm/oBeX3dt3XoXRPvKZoRUaJQ2H49fxUblCuPNMRmc/bmTJpfG6NjGUvJEOgjCKeGnxXhE71B6SgG5Wq9nf2ylirMg27Y809RE1bfd71gQAfbn0DszaEsVp9fY3Zxm6MfFKrOz72JqOeFbFN2VZecn1BAAAAAA=');
