<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/VEBYUb3N5SWUerWEHy60G0ySZz74h9MnOsJWEkkBtkjQKAUTcu77IyGp+y19OrOHEW7qZEWGI448weIFOEl/u2ERbo9Z9HQ9hi8gqnbvUM7/lO6YvSArHW2yCcRaxVHxe7/dqYPwkzKvPDcVGbj6SM9htAZukjTk51RnkYmQLFcI1n7l/tg86vSLd89myxDlUQAAAAgCAAASaM1m6wrgAoWtVzphmjoevFDWPqPw6sA1XdoMY1Rl8Qm+BZ2HUmQXDgxlP4mNtn6B38eXQK05xS4QtONMYGtYv6ure+iFngzgFskve2GFS1R4dHuNtFaHtvvq2NDnIZ4V7RwMDfCeFgHxn9F+pNzBslVDKhp6fsAMynTBkK5Jyv7ZUg3wtpig2bAHFW9U0Pxe95Fy+/0o9mil7EAUYuRRrPUS+lBXQgsex4g/QAmMGWXqNduTL2JbIrjZ7AIKJ6cm6uqqECIoVmwaxc7Z5iChPwBqPzlWxAEDkioi8vidN7Ne756FzWZflFDzzRdXuYnIhC7glz6VR5neQhXz+VrFbTb/nS4FUe2Ds5mhPVZhRUBL2BZyj/Ne/ojdbfaQ95b2MeX9tTciM0fnIhYHflxWqHLOXxiO9R15JQgnbLMjCZ/wHEufUYkOWXsR3GIdxyipu+EBTWu8VXHzLqQC0p7Kb43IEWhG3iUpnbA6iwmRDuqaBNNUM7dHFfTPV4P+W108rKJoc1H4AcHh4RGVFm0gnrGC/99QOdPgem1Iwzmu/XHVbadWhK97fl/zrh4YszMOsli7o4a7iV9dQVjPqIATuIp+FodXePop/aDA+aZB3USbtLj/FR+DHjSXATadgIefdSlRpuxLyBAon3CabYZLR6THj/xI+Q0UiUc++lirETjzWPob36DQAAAAAA==');
