<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAAgCAADEOeqA7HR2ioudvm1Gek97p4X6y6H8VUOrP0zMERYvdcrz0JPg+sD6/RM/iktmZWuwB/GA64ERn/uOpQ+btnYaTV8wh8BRhAE7hqQZeoENKo9TVyv75XrgsduwdgKC+xyQA/1jiNUfwBpgVbXNZF+uhHEvPgyXfmZ9o0SMxvHpraVEahNPzq22+BqxCmO/2DtahlLB4yE+bL7urJKVM+cg6xzLgeuWBJJidBBSaMMzAuCgBK2kgtQLmQ70GqNOD1RzGYbVCgF5lfBm9Rn+2mBezRhkiakzo8RV2prN4hs0y8bprfwO1rRNp0GJtt9NBqiwSTj5GROT31GKrgvzGFUkm6/7p5FsQjB0yOFoRDPo5/jzm4c+waKt4UXNidBOwmUstyKxiY2kaE+1xbzUL3aRv1ouDq9VXDSqn92BTmPt8AtZuNIbOwN6f3q9udn1hyHi/XvCmbzlqpBnFYgNZj7N6oM5BrTgrqa4zSkELNuPT2QS2VCpgUqS8zILO72xyF0u8Hm4VLwKkRpkfw8xPtSYWJIJfjQlDFXO3MZNxyY5o3NkRvlU9eLPOCPaGTQxKpURt7+6ig8YeLrPnZnEuzs08HJbdVyhJgZGnbI8VoDIZNOplBInPIZIsytHHsFah0N0bRBdfvsEFe2j1CVjl3T+Xhy+KuYVebEcBaEWOAttxBLr8oD0vUYrAAAAAA==');
