<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAADgCAAD6YdcIzEMEFBb+G0icQn9b5PYWHtbu1EbfIOAhm3MLWxQ0/syObLa/kZoVhVTr/usU4Na2OMsPl82J9FIz2ut280ckwM4MtT3AKvhGrLDje1zyCNak97m9rCXAj/YIpL+MfHNC1OzEEIbYP/xcJ5kBJDMtiDS/EwBbPr+7YHe4/8V2AyYanH8QD8UsXukKR4JuetCSMxNPLbz7IglCvxiHWkNDSjzf/9ERRiHmhoOVLr/iSKj+a/JxpN7j4WcWut9clISZGrnttVx2ST8nnf68PQvBDIMG7AiT0g4HUasG/ZokvaAaaWWKpRNwPPn09ne44p3m6gC7ezsX4/5+QKh02KOWvRaYgEPa80XNsflTDIKiCJi+FilMT+dht+o6nKGJNHBxdH1Oic9kStERWUBumfNRxychbNvpsp/Hqu8h+GbJ9W3X9jQne8+nZpaxcy6WRqb4AjAE/mx/ezxlCOja28oGypeBLfW77a8UlmkaBHXoC8/VBaJl2AjOkNT9RMMTk3eSCpjDtI3JxxiJf6Rc/iWN3tbM+KJYonoToD6jEc0d0p3uln0CBfoVRQyj0N2f7nbFqAtOyTSydoD+Grrjg52wTyGlWNRTMfXUb+hDXkrF6b3m+n17XUdMz3qxEbzjgno2SgRNhDzO6RnEmUlgdj5g1lMo1zJtVVQq+Db1u/jEzPoql7h+yXVR05LhKQpRY33ToJ3gIfifohj0dSklnKaVtQopWBA9O0JwOBLTul4bBEA32qYoAAAAAA==');
