<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAADACAAALQEXEzHWjrSZBwZdFXZIq8iYIdEV/V4nckGILHGTKYck5eO9Aw4TQsYj9NIurNZfhKD24yOTV7jARzO/8G70MGJSUnjfOpqrTnbyi48+OxB3RWh2MeciBibMwAckdmo8sh6DQsDOfKhYph7ZnLuNwPQbUrJ8Pp/Ylc9ACgVIFQ0eRDBI6+S8ejJG2oqjjmtf8QtiPXuiaYTnIeLAWeUfeJbK0U2KItJMHXOWlkpq5KAPrMV1Mz3bQIazaxeG3LUJ+QyuXgehzTDAZrJybnPJDXAi+BzUjthR0YahRhxbuQaqupEh90Elktvv8FEcz3SBsP1qwRyD9tGy3lVc14pEn0Yqn9h3He2mXaDBAg+DfsLcQN+fHWu4GD5R+ewTbwFlD/q1Dq8am0IPrVDKNlqkoz7GVAKTwCbWsA2ONcwprlzduLpgT575MA4CuGpt/oV3DgwE/6t6GPPQhW5GIRx+dVJR2SAfDA9ZmbUV/lu0c36ivUZ/3vsxFCH06H8BWhsfuRBSBKBuDEnhAtr03T9l+bh51Nl4UrQ+Tr50yLVuedTuN3TBCmnbz8kzzYRK2Wh7SG+g/N4hxhOXrewFSyKGyb28xdQtjfDX6o+22fmjQpS6fEvL08s0i5Rkrj8ntdqKclREpU3pAz0EXP+/hmjnGpyCFt4xasDR6GHCYkRiZ2iyJORGrE3evp41K6P+RqB2LQtyvEGlrFGPJ0Xkhc9mDvlT55YVzPcshtoqrODqafQAAAAA=');
