<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAADgCAAB05UyB9N3oS5TaoyxS8TM1xLQtg9PuecXjCB/w4p5kY2dvSZrR1X4aNaRySsqMqi32XYRvuzO2cXCnH0UptCwSwXkUqSocE1MCAHZehgplf5JozS9RYYHBMaxXRcJLvJn79tYrwGHDoEBeDjEFx9yUnYY2vSpOa2ntRAPI2e+qN057+wccmVOCyY6CHcAtBIB0I0f1gee0rbmqDHsmolnaWU1gpKWQQf2WoC/A0SX17i24rxVbcOqx+dERitVH8UD0VTtB/+ZFC5RI0UrCNFDOS8eq48ldIHYvQsA3YNkZzzrHaG+ep2wFfLHwYEfpoW0s/iZrz/jxyFsEme+kzT0bawKeuUftHibptwlVqbVtSak87DBB3WZoxTsAu+RTMOhuOnWCy1vfOVCXILIuE0NYlb3uMeu4nY6fmq+NMQz0KZ/5jsASKV5WJic84TLEd+SmmwHaZ6Cv1OMnrTbDZ0yjFCjNRexT/o9QVl8wu/5QhpjAYkUlAFjYD7UYRMyAbyFbwiSuU0D/gmaudE0TwwgPnmfl+YsSWitrcpdozU9Dh/dczLtllPi95FOtuxT9CSEvP2g2LAmrhgHQVW/+NERc0r8WkXNRFp0hc1CJvuanGsMclviWKx94J+QogvIxrsiZUb/mKZcrUOgl9JnMo1sGrLSmBOOHbUIlcFnt/ynzxMuwBx7DDZ/lT+jt5/HpBJBNcVhBWPQuUjCZYMYkqzZydpMhLL8QONlFKjYvFD+/dq35F0D1+MkYAAAAAA==');
