<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/B58dJM6AqWlJffzg4AcCTLnHrCf8eelSA7K2xOI5tKtg2J74irTPt8IakUuICRD8r/nHh5CbJb9OSPiL4lDhzlQ7D2XaVxmgWB2mI2w+kA1BpgBQA8YsxRoeYdXRFIrNThFjIOxWBrlyNvhIRaxnlbIMnJ4gAWw27Nls7NN/cmyBeDYDRpS2bUa+IWEeGelYUQAAACgCAAA8tHQ0ykTFxEOzIWq4IkbQaGy/gYFPfd2wOGPJm4Xos1xcgVvmGyD9AB1HL6s2rJvtOu6CcVe+uFUKYI+6nKeuPajye2O+E1nqAk23y5MrbAYWmlIVxenijdjtH3HN/Omnt9Wcty2HHeqt9UyOdPaPl2tv7E1F8cLCtol9lJ4FzVZSM5gpvglssn9Kumh8g2YZq5Md2B5zJy4VDYWSAuoO+y/kFMfjyNdDUFRYMoIXgWLlLwme5xuTcIz/75f2oldnOo28U4m4LkIQLE/zOfTj0mHbmmte3FFb/8yhiSlUznKObUQtlR6x7uFG1tGBZiCZTz0d+4n8FyMqdt9sFroGrbtRMV7mBFm+Ywzu0tMOtZav7BcqU+m/zaZKN+XRwQRKbzSHPUsbF6ZvzyxdjCWyKvvOfqzQqnxAcrTIEpy+PUMhm7NBEnWq/8Vag+TuX6dnNgPEWcQPwr5tXX/5e988RQ/KtLxayPgeI/D6bwXJC9hVzVAS2pKWvRI6SwMOHCP9ydKYmy088ImBkTS4zBMuH8BphgQhpPE0tS+zyl17ZGbn2S76hntcDDvimGCIN8rohrNds9zNnKqu+6c9836t/Qp/mAQOwYkG8Lryd3+n3tMgEmTRYpmgyA2+ApC9TD3M6gGK5B0icUpLZw9rENCmSafAFd5BrfdrmnDdxxxPm0kEZ0RtJkZgRU7BNjwgXClTvaq4Cr8y1QWq6bJRpRSHUIB5CqlAk34AAAAA');
