<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAACgCAADkMesJt5a0+Tu8XWZdGhR5e/1NbgRoliFvTEEOJeAZ3gecDLpmCnLhCDJuXsf3czaUE3QwAQbWqsAK/Z73vVIy0j68vCLPoxAXzzrXjbRFgqitT+57BXRZ5y0xQv6NVb3AEqZgG37P97BsRlkSuUP/CPpdMKiLRILrx52XU0dKGiaK8VYChPhMXEI6JdZIRWr35UdBlXhY/01QqR4SXtcTf7ti8nJnmuLJgvtg2FENi55zY8XrWS4VqxDmj4+8lT1GPlF6gEhvxyOIaQ6GyNSsyROjERk/iR8ccHSO2G+Vve/58HnO7hRNKMlk/Jax1Spay4/HrJCEN1Tdk6ZFWS4hLYVjfzoht7tfEYXzYc4oDit8Jwu973ovd1h4ik56aNZZWWGAxRCSY5L/LHHVTdMkWOPgfaXHfzoHxzIq1lrgua9C62zdaYd82JCU9pQWEZo4JGzvNOEYYyKWwHYH4R+5yvXpd/iBcfVkMesidNXgkwifT/J2WcgWDmb8mZZEjg2SOVQqHosDkyYEsedgXqjQG1HFGTh+BR5rp4+/1WedIzupXledaySlbVYVHRFdRRfcmAZd4eMigtmO94p47BiGG6ac8DHZLs9p0xj7Ahs8NFdH8uQWbbzFOKP+Zk92F8w6Dp5OoV3XnHPx0mcckStRWAcJ9ZiqqSHoZj2Ro1UnsqL3RTFNqw4MdMv5o2A1tBrP/SpQTKdpgFRsNfKb/Tsd0nt26IFtYdIAAAAA');
