<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/Nnvcz3RG/S3jOHq/mCiK5GJh37Dd9sAHK2mQ4XXU4mmITLsiYFGWEqaTfW5mYt1r7K59A4NzPdA564Wn4KooO6sdpMCEFz3N/kP89GPYL9Er8MapCJjP6dA5lRqJBEGdg1dF364CVUwNE8WWvcQBiUawnxG0ifnbvhqBM4yJZnInlPdB6+bKsSeupnLrGDKFUQAAAPgBAABdFI7KUUtiPQ1kzigeh1TmN6hm+WKA4nPaEqa/X31ZFHUZdgRFKAJmMLiV/Dcgghy4EpZpNDRrXzE5by9zU3ksV5VRuV6pC6CRwP0fgMhp4+ALl2wFilu4VoqPPkOO6SXgSq+VNWtAn93wy6yDylfjiPDWZswzFSv/YIbS+UdlHaCdoeE9WyblaRyiiriYyVkqwv2U2Ja63rXu0uijOE+XiIm9OPLk7AYZnn1LKNRcc1YJxeOwEEKFroALUdG4gP6uOGuDXEMBMrrFTv8RnQSQoDx9K6h4ivjgR0bITlpie2psyU0i/+Kvdfn5x+kXLY90uouAC3eYLY+hQ1GKFsptAEDJewIuo6CP15TMP8vg5++7gnNoity70RrxCMm3AqzVDUJI5Uuk7fiyl2DPK1amggb0z3bOLCl7nhvlEERRmynGr+MRHHGcOTlrO6TvDmNsvtvSeEWkNx7l04jYWCpROj4h4dm77KqHPq6MdiNW4XnxGW0PVl3iAOR/pGCrHuUlv84OITh4tEb+iW786zx2+yxeMorvD8kzy1oVfKNrGYeQVzkEUEpHAnwfcNAxYhmMzDK/xbn1rth8RPbJ2lSwkxLcHxbClqZn+vzhken0c8z1PAxFJVcmb/5KuBKqPoSuoqm12OBjiNn4ENhEAbEKlvbJCLWJQukAAAAA');
