<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/JP6X1bnpji4zdREPsUqwr839hsi5lG735f48vilxgIMtUUe7rcIadnGfTKcZG1U0CsF0+kCqjFYfivlzQuFfzr97sx5zGa7tl12Ko/x1V8bMLri7ZIwIVYNjo5jM6gAVUjFd1VOO315B4GkRg/XRwmsxodCmZR6Ho1fxZNAycWjTfFH+bqfyOZldZyoeSUsCUQAAAEABAABdrx1Oy9BqPyszYt4iggiHsZZU2grrnvwi0Z6TkalyvUD1Ky76vmETj5hYkarYtpqyvLpXPVnCKDD1VRo8avzKQvnHQvmbc+pR4uaWp3WBwfEBPMHSGQg0nw46yUlIIXqqFwu3fNtdXSW6ukpkTcObeDyxdFpXXBDqrk/eX1eFMA3dvbTxI9cZbeVu6bSSYfo8qHd85LclPJnqOfdapsX74ODaP4OV3hYKdX8XThp9CWWitsDHH89ntU0BW2d9cY96xbrFpc4v6wbP6KP9k1t8nQNk3mmlzlrfuijeDRu21ACCDwrUipPnWNBf/hkbn7/wiz2gvul8sZZo6sSz0bxEgraiYdTsbdRdELsER360BZC2hVy/Do1aen1z1NAmT1JcDYafF1iJKnUQ0egDv22cUbIch2sEFeMmNMU4/2vtggAAAAA=');
