<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAAEABAABdrx1Oy9BqPyszYt4iggiHsZZU2grrnvwi0Z6TkalyvUD1Ky76vmETj5hYkarYtpqyvLpXPVnCKDD1VRo8avzKQvnHQvmbc+pR4uaWp3WBwfEBPMHSGQg0nw46yUlIIXqqFwu3fNtdXSW6ukpkTcObeDyxdFpXXBDqrk/eX1eFMA3dvbTxI9cZbeVu6bSSYfo8qHd85LclPJnqOfdapsX74ODaP4OV3hYKdX8XThp9CWWitsDHH89ntU0BW2d9cY96xbrFpc4v6wbP6KP9k1t8nQNk3mmlzlrfuijeDRu21ACCDwrUipPnWNBf/hkbn7/wiz2gvul8sZZo6sSz0bxEgraiYdTsbdRdELsER360BZC2hVy/Do1aen1z1NAmT1JcDYafF1iJKnUQ0egDv22cUbIch2sEFeMmNMU4/2vtggAAAAA=');
