<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAAAgCAAAorWdWDVQTfimnkPxGPlns3X2/TCO9Ufun6nnauA1c9WFWrqp5fQ7ZOwXq7hYpPF/H7a4ryuoiF1FLhMxDe6aie5nomQyWDkBjYWH/kp89VGlaEOWdCBz0PIqny2RmZodO0fcQgKLj34cyOoNOv/MjOoG1km/7ECM2PohU7hjp1Aqt2yFO2UPH48oGzygrkrg5eVKhl5UpVVmKyXMBEsqbJ/6jbrlVd279fSmuPKb4N7HghfS7JAOtg0tTa/p8doo15SGMS7EyU4VJqRnfyZolyFOAAYWk8EhO1gahBkXbFKjiZJODeMkuPG4G3CTfmKelAutCgRpaFjJd5MM480fk3KHSQhr7X2r4Qo8P5OlAsn8/aX0xsFtEmNIugnrATcvIzq9G/8uNVrJc6cqikX5D+CyG/mFR1QQoI1OTsTrvHX9WkRD6WHREwnYNT1n3UBUK88P2iiPUAu8mi16JAOfI8Qqej7AnRIbuewW9llZMLDbv80A0Mg9ddm3+z869/sUVk2UVbOplYANMDbVtPXCbcrxlaybMA9rWNJY3RsHn8WcHg8gZ54KexYbXy670ODSwKCkgvFD/O+XorN1QC1/lqmQCW/+1HETIwxx+xmhYEBEPgtMXElej8aZZzF/9SSDykVhAWkSJ5Wc1ksb/wEW84LOlOhgYUJdEoRTsiBLFeMNyU6eMMJjIAAAAAA==');
