<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAADgCAAAf+QNIRVGtMMwK2GIBw9qHhVuJtSPOHpvImkOt5YYi7Puj/a+nqlS+TDDIAcxcVgSEnbf0Et7R5PfAVdvUrTSxq9CEDFbyz+rFvoKUDPx5a5nf+SxWhBweK7596j8qHVwo1gwgGSDLeOnslRRkH+ADrH2bQqiYWLBZjQksF4NVOg9dfJN8MY/L1OSqzLAWcan44hoBPPw2EW61pHDB1U6ky6Dr+xVaSOWaHEsrWcpWBlsyRvipD58AxrOhagk+SE9+veX4es46COYtpf4RgbMBuPx5s5k1IkyRBHkg8sV3HQ3yORclOHpLVFM+uUMPxeYdm49619GLH2++n83UaxEG+7XPco5bYB9KE8BXjzPUF5j4Yu0CRO0bXm1yVxt0SWvFMhmTWytNSpRFzslDbRb01n6HaSNzbhgG42hXyGWdRRGYd1ZYrS35GNkZvyro444KlyBerJtZB5B+JptkOQEi+ITF3ofKiBSUJMnJjwGfwrqFTHJTdPFdBNDJAj+YZXVS7AEZmKuvSwIsCevAYiaG4hfWZiVWcbDb0/qAUZWmEp4aN3aGLttoG9lg3p40HdPi3oyM5vTEJyqfx9k6U3j61/t5FEesYe/gubqRRwbXHa5Xt/YaHozivYDVjhYYvmdA+9qmCXYXZuXs54wJg5y3X6EeJcuhzGPKCtBTGMh2SJ97yxyEcma+dwvX7uWNiU/hkVNtSLrncioe0izZ/2WGqjligbOEj572NxQo0fducxf800XHSZxHAAAAAA==');
