<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/whp8NMCTTu5ErqBZWQqK1w3xTm2yPdQFI0RiHnnyk5XArCv4MgJUWi0QpJBVt5mxBVn4N3GN4J4P4AQD4ET3jnRTFrQQpwM7FybwnerRq8rBqWDSU1l7nrQKYEB2KrPeYgEXMWce8/l1vZvnrtitMstX+OREz1WA5kdbWQxRfLyl2sM5hJZ2M/CpuqdO+qQJUQAAANgBAACNfSGT9ilddTdu+W2AiYcpVNN8e0X3hyorqb4qRa4JGKeX7wlvKUcxaiss8NsmVUU6MpJ5dKt789srvo5vKCrzFKFu1NOIKs9hGVAEKc10G9tpQCiLhRxirAJF+EGE5J9AUnK4dwhps5c4/Wo1dvEqdtTBjaQNdfm4c2FH8Sg+8gEePNgOjGm2DY2I9JIZjiejDfYy8aOzXnJe88Yei+FbdiZfi7iv27nl4Cah8mgb139GG+Aszul8wHReqKuYWFNKXjZo6pn3qN4j5HBZH/ObxGMOVbpOLUH7vR4FvDFF/OWbsuH3UQCUTVC9NbWveI6T/ZJtlXDr1ZL+7JjCAgek1t5nsd5X70PGnp+3mZkdYNfsrbPHg71InRonwfIheJik0xWRba6GjAHDEiNfQPUTH8XMSQ8qapVft8a++ThNYuMvgksgk2flCqxKw6MUtoS2jC1rClK3TZgrHHevBekEdM5R4UtvPyepdTP8/kPeZQHQ/2da4dEcvuX2AasMro+zFKr3JD7tlxT1AJE/f9BtJAKUVUukqnvLwHU5KfYbvGWawGashoatKXPdeYCS4rotD+lU1kUAzIp+5LQjnYfq4gMtPscFEE5xCL4ByPo6BrEomsDbOBNVAAAAAA==');
