<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/X0kdnPPXHrjTHaCCMeRyn9kMCNMW9nKKBzDC0UsaCna/mDrMcnOoHtQ6qKYZBOvlWShNrlmXWZ3ViI16XmD+2PJ6LKXKZdidqPEVQ55ZZzYKVhojKIWdFntaiNn4Hha+jmQVqNYVd/NRK3y97EXiz3Hpp+AL/JPbbqoo1svl95RQlAntuZbjbLvFE3tfuV1FUQAAANgBAAAvn9NETuVmr2GNIW9vXnM843M5MXPiv5rrIO0Wm8eZT//cXMeS/cJ+359EfUe7azhAE6hMczXU6IOGwbaqzyzZOvip3NhnDnHTyupBYYVCFjt5eSYj5BBLbiLoTz2VLBX2E0YP0F3zwBFyo3T7tiO/xFqJ0wKMnRDHgkjUb9C74d1BEVFck+87xsrjxaImI4rbnI1uPSRQSFGQGo+Rn/srbppLUnh2ofFcD48xnVdQjdnzjmGT9eIfNnty8DqEii/9vrq8LlSkbbNMwSFKl7YFWpT3eqYswOVuIU1a3mmKHylQh/tzaUo4F6EI4gwIejK6ZLwi6pRFQxwZECzKuNATrpec+cIlvkrV6OyHeNZLqjy1xyEdtwz9TLx2xdX9K3y5IzTQI6HX3KMzOZxem/MRR/Og7W2KOU0djwaX7ihtHFsaL/B8CFwR51KWYF92dgUP7v1J+yfiaOfg9/P4Dv9l7JbwH6Ii+kC3klPHY0BEU/UEDkZuolxgT8oA7xEo/0kUIODA0hbdlsA0/4iRFFj/UDeCNdKkewUsPTMA1hCGOGilOlzjelCCTlGd1SEelJTmHbub1JNldDVu/PaKcWvgtxMJlkSx348QGsp6yu6Ypsjz+Q36m8NyAAAAAA==');
