<?php ?><?php
/* Copyright (c) by Techport */
if (!function_exists('my_error_handler')) {
   function my_error_handler($code, $message) {
       echo sprintf("Something goes wrong. Error code %s. ", $code);
   }
}
?><?php
return sg_load('08FBE9124397C062AAQAAAAXAAAABJAAAACABAAAAAAAAAD/7EbeEC1vWFpn4nmQ55VS+JYQiVAhl6EXbh+V7J+JkF2gjxbRdU1xm711qH7FeVonhxTK8df787HAiQvKqvQ2gL89V4O/lkYSCVYYGhHCjt1qNuRpaSY3YcCGFNn8KBpUJnBeO/jtwGh1GQ2xiKdCLJ9YDCY6eBBmS5jMc3V2GJzz1KDzYBjZJ7EzDJzUpLX6UQAAANgBAADVgJxYi1WaFa23d20NAiHU4MfWb6V942xqcKAEH7xuCew2pitutpGosFQwXX7gbnThWfT8bcd64ZJUIg51xieTzXKTPsy4xpLb9+ASAhAoypHjpMsFtFINDtoUElISqx9IWocO8rCInkbA0YPQ4pJUSvKhsmrKm4oT3QL9fAm6foXL2IQ2r8YYqF5LNT+xfdyzcZa5V1LJgH6QuGRE/jXX1HMLKMzpgD7fszStZqsar7KVcUAobW2iN7OrEVbdrbvqPmkRQdsrUKDafNwq4F23S0z+zgPzYP8pPu8lmixHi1mxZ0WSdxEbS2zjz0R1sbit4OLM3jRRZFxkFBXBwc+2VZnhm4i8TMm2oSRjJPs4nXI4Xx8ICXwIiZldqFjdifXheQXrh5jRICw500hnpjcEtPnDiBkLhfdzi/iIRBZOv1xCzipYHBjYLeiYcfSneYvZ8vT+KIMsOKgyV80eLyaQIfl0+4roNyn/OgGsCJheSf6Q+4fopTIwnUi3aYzh6UkRwYhU6uSmjKJu9jrSKmRQl4sXn4ExSo+jirzgN43+tHq64PdcoYY177tqsDMhc0VEVwfzAPmhnhxo4jn8YebwtZnuuh+nWvnR6h01k10jUirzeaHAaBxSAAAAAA==');
